/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  es: {
    nav: {
      home: 'Inicio',
      philosophy: 'Filosofía',
      classrooms: 'Aulas',
      reviews: 'Opiniones',
      contact: 'Ubicación & Contacto',
      aiAssistant: 'Asistente IA',
      login: 'Iniciar Sesión',
      backToHome: 'Volver a Página Principal',
      changeTextSize: 'Cambiar tamaño de texto',
      changeTheme: 'Cambiar tema',
      colorblind: 'Daltonismo',
      language: 'Idioma'
    },
    hero: {
      badge: 'Centro de Estimulación Temprana',
      titleStart: 'El Lugar Donde',
      wordLearn: 'Aprender',
      and: 'y',
      wordGrow: 'Crecer',
      isAn: 'es una',
      wordAdventure: 'Aventura',
      wordMagical: 'Mágica',
      desc: 'Estimulación temprana, desarrollo psicomotor y aprendizaje activo para niños de 2 a 5 años en un entorno seguro, afectivo y guiado por la curiosidad natural.',
      btnWhatsapp: 'Iniciar Chat por WhatsApp',
      btnLocation: 'Ver Ubicación',
      sensoryTitle: 'Sesión Sensorial Activa',
      sensoryDesc: 'Motricidad Fina & Coordinación',
      live: 'En Vivo'
    },
    philosophy: {
      badge: 'Filosofía & Metodología AMI',
      title: 'Nuestra Filosofía y Metodología Pedagógica',
      desc: 'Tres pilares diseñados para respetar los periodos sensitivos, la curiosidad innata y el neurodesarrollo integral.',
      c1Badge: 'Desarrollo 360°',
      c1Title: 'Estimulación Temprana Integral 🧠',
      c1Desc: 'Integración de hitos cognitivos, motores, sensoriales y socio-lingüísticos mediante exploración con material concreto Montessori.',
      c1Footer: 'Circuitos Sensoriomotores',
      c2Badge: 'Conexión Continua',
      c2Title: 'Acompañamiento a Familias 📱',
      c2Desc: 'Acceso exclusivo para apoderados: bitácora diaria en tiempo real, registro fotográfico de logros y comunicación directa.',
      c2Footer: 'Montekids App Familiar',
      c3Badge: 'Innovación Pedagógica',
      c3Title: 'Seguimiento Continuo con IA 🌟',
      c3Desc: 'Sinergia entre educadoras de excelencia y análisis adaptativo para sugerir dinámicas personalizadas al ritmo de cada niño.',
      c3Footer: 'Planes Personalizados'
    },
    programs: {
      badge: 'Programas Educativos',
      title: 'Nuestras Aulas y Niveles de Desarrollo',
      desc: 'Espacios especialmente preparados con mobiliario ergonómico a escala infantil y materiales autocorrectivos.',
      cycle: 'Ciclo Escolar 2027',
      openEnrollment: 'Matrículas Abiertas',
      consultBtn: 'Consultar Cupo',
      r1Age: '2 a 3 Años',
      r1Title: 'Aula Semillitas',
      r1Desc: 'Estimulación sensorial profunda, primeras estructuras de comunicación, motricidad gruesa exploratoria y desapego seguro.',
      r1Ratio: '1 Educadora por 5 niños',
      r1Cap: '10 niños máximo por sala',
      r1Sched: 'Mañana (8:30 a 12:30)',
      r1Assigned: '80% Cupos Asignados',
      r1Free: '2 Lugares Libres',
      r2Age: '3 a 4 Años',
      r2Title: 'Aula Exploradores',
      r2Desc: 'Desarrollo de lenguaje activo, socialización cooperativa, pensamiento prelógico y conquista de la autonomía cotidiana.',
      r2Ratio: '1 Educadora por 7 niños',
      r2Cap: '14 niños máximo por sala',
      r2Sched: 'Completa o Media Jornada',
      r2Assigned: '65% Cupos Asignados',
      r2Free: '5 Lugares Libres',
      r3Age: '4 a 5 Años',
      r3Title: 'Aula Creadores',
      r3Desc: 'Iniciación a la pre-lectoescritura fonética sensorial, motricidad fina refinada, proyectos científicos y retos lúdicos.',
      r3Ratio: '1 Educadora por 8 niños',
      r3Cap: '16 niños máximo por sala',
      r3Sched: 'Completa (8:30 a 16:30)',
      r3Assigned: '88% Cupos Asignados',
      r3Free: 'Últimos Cupos',
      ratioLabel: 'Ratio:',
      capLabel: 'Capacidad:',
      schedLabel: 'Jornada:'
    },
    testimonials: {
      badge: 'Comunidad y Confianza',
      title: 'Familias Felices en Montekids',
      desc: 'Testimonios reales de familias que confían en nuestro acompañamiento.',
      t1Text: '“Excelente atención y metodología. Mateo ha avanzado muchísimo en su lenguaje, autonomía y motricidad. Además la plataforma web nos mantiene al tanto de cada hito diario.”',
      t1Author: 'Valeria Quirós',
      t1Role: 'Mamá de Mateo (Aula Exploradores)',
      t2Text: '“El ambiente es cariñoso y estimulante. Las maestras están altamente capacitadas y el enfoque en ritmo individual marca una gran diferencia en la seguridad de Sofi.”',
      t2Author: 'Carlos Mendoza',
      t2Role: 'Papá de Sofía (Aula Creadores)',
      c1Val: '+150',
      c1Title: 'Niños Felices',
      c1Desc: 'Acompañados activamente',
      c2Val: '12',
      c2Title: 'Años de Trayectoria',
      c2Desc: 'Educación de vanguardia',
      c3Val: '100%',
      c3Title: 'Familias Conectadas',
      c3Desc: 'Monitoreo en app',
      c4Val: '5/5 ★',
      c4Title: 'Valoración Promedio',
      c4Desc: 'Satisfacción verificada'
    },
    location: {
      badge: 'Ubicación & Contacto Directo',
      title: 'Visítanos y Ponte en Contacto',
      desc: '¿Quieres conocer nuestras instalaciones o consultar sobre cupos? Escríbenos directamente o visítanos.',
      hoursBadge: 'Atención de 6:00 AM - 6:00 PM',
      hqTitle: 'Sede Central Montekids',
      address: 'Av. 5A, Provincia de Puntarenas, El Roble, El Roble 2, 60101',
      scheduleLabel: 'Horario:',
      scheduleVal: 'Lun - Vie: 6:00 AM - 6:00 PM',
      phoneLabel: 'Teléfono:',
      emailLabel: 'Correo:',
      btnWhatsapp: 'Iniciar Chat por WhatsApp'
    },
    cta: {
      badge: 'Admisiones 2027',
      title: '¿Listo para impulsar el futuro de tu pequeño?',
      desc: 'Cupos limitados para el ciclo escolar 2027. Agenda hoy mismo tu visita guiada presencial o virtual y descubre cómo hacemos de cada descubrimiento una experiencia inolvidable.',
      btnChat: 'Iniciar Chat por WhatsApp',
      f1: 'Respuesta inmediata',
      f2: 'Recorrido personalizado de 40 min'
    },
    footer: {
      desc: 'Centro de Desarrollo Temprano y Estimulación Integral Montessori. Fomentando el asombro y la autonomía natural desde los primeros pasos.',
      certAmi: 'Certificación AMI Internacional',
      explore: 'Explora',
      linkPhil: 'Nuestra filosofía',
      linkClass: 'Aulas',
      linkRev: 'Opiniones',
      linkLoc: 'Ubicación y contacto',
      contact: 'Contacto',
      locPuntarenas: 'El Roble, Puntarenas',
      hours: 'Horario: Lun a Vie 06:00 - 6:00 hrs',
      copy: '© 2026 Montekids Early Childhood & Stimulation Center. Todos los derechos reservados.',
      privacy: 'Política de Privacidad',
      protocol: 'Protocolo de Bienestar Infantil'
    },
    auth: {
      tabLogin: 'Iniciar Sesión',
      tabRegister: 'Registrarse',
      certBar: 'Plataforma Certificada AMI • Encriptación Biométrica de Grado Escolar',
      communityBar: 'Comunidad Montekids • +1,400 Familias Conectadas',
      montessoriBadge: 'Montessori Digital AMI',
      heroTitle: 'Acompañando el Crecimiento de tu Hijo 🌟',
      heroDesc: 'Accede al reporte de actividades diarias, bitácora fotográfica de estimulación sensorial, canciones infantiles del aula y canal de comunicación directa con las maestras guías.',
      heroF1: 'Monitoreo y bitácora en tiempo real',
      heroF2: 'Registro de hitos motrices y fonéticos',
      heroF3: 'Portal seguro de logros y micro-premios',
      trust1Title: 'Privacidad Blindada',
      trust1Desc: 'Cumplimiento estricto COPPA y GDPR-K',
      trust2Title: 'Asociación AMI',
      trust2Desc: 'Metodología Montessori verificada',
      trust3Title: 'Soporte a Familias',
      trust3Desc: 'Mesa de ayuda pedagógica 24/7',
      schoolCycle: 'Ciclo Escolar 2025 • Trimestre de Primavera',
      loginWord1: '¡Hola',
      loginWord2: 'de',
      loginWord3: 'Nuevo!',
      loginSubtitle: 'Ingresa a tu cuenta para continuar con el seguimiento en vivo de tu pequeño explorador y revisar sus bitácoras sensoriales.',
      googleAuth: 'Continuar con Google Workspace Escolar',
      orDivider: 'o con tus credenciales',
      emailLabel: 'Correo Electrónico Registrado',
      emailPlaceholder: 'ej. mama.mateo@email.com',
      passwordLabel: 'Contraseña',
      passwordPlaceholder: '••••••••',
      forgotPassword: '¿Olvidaste tu contraseña?',
      rememberMe: 'Recordar en este dispositivo por 30 días',
      submitLogin: 'Ingresar al Aula Virtual',
      noAccountText: '¿Aún no tienes cuenta registrada para tu hijo?',
      registerLink: 'Registrarse Aquí ✨',
      regSchoolCycle: 'Inscripción Familiar • Ciclo 2025',
      regWord1: 'Crea',
      regWord2: 'tu',
      regWord3: 'Cuenta',
      regWord4: 'de',
      regWord5: 'Familia',
      regSubtitle: 'Vincula de forma segura el acceso directo al aula y a la bitácora personalizada de tu hijo en Montekids.',
      regNameLabel: 'Nombre Completo del Apoderado o Tutor',
      regNamePlaceholder: 'ej. Valeria Quirós Fernández',
      regEmailLabel: 'Correo Electrónico de Contacto',
      regEmailPlaceholder: 'tu.correo@ejemplo.com',
      regCodeLabel: 'Código de Aula / Alumno',
      regCodeBadge: 'Proporcionado en Recepción',
      regCodePlaceholder: 'ej. MK-2025-EXPLO-88',
      createPassLabel: 'Crear Contraseña Segura',
      createPassPlaceholder: 'Mínimo 8 caracteres',
      termsText1: 'Acepto los',
      termsLink: 'Términos de Servicio',
      termsText2: 'y autorizo el tratamiento bajo la',
      privacyLink: 'Política AMI',
      submitRegister: 'Crear Cuenta de Familia ✨',
      haveAccountText: '¿Ya tienes una cuenta de tutor activa?',
      loginLink: 'Iniciar Sesión Aquí 🔒',
      passNone: 'Sin contraseña',
      passWeak: 'Débil',
      passGood: 'Buena',
      passStrong: 'Fuerte y Segura'
    },
    ai: {
      title: 'Asistente Virtual IA 🤖',
      online: 'En línea para responder',
      welcome: '¡Hola! Soy el asistente de IA de Montekids. ¿En qué puedo ayudarte hoy? (ej. Horarios, ubicación, o contactar por WhatsApp)',
      reply: '¡Excelente consulta! Nuestro equipo pedagógico y las vacantes están disponibles. ¿Deseas coordinar un llamado directo por WhatsApp?',
      placeholder: 'Escribe tu consulta aquí...'
    },
    forgotPassword: {
      backToLogin: "Volver al Login",
      title1: "¿Olvidaste",
      title2: "tu",
      title3: "Contraseña?",
      desc: "Ingresa el correo electrónico asociado a tu cuenta de familiar o tutor y te enviaremos las instrucciones de restablecimiento de forma inmediata.",
      emailLabel: "Correo Electrónico Registrado",
      emailPlaceholder: "ej. mama.mateo@email.com",
      expirationNotice: "El enlace de verificación expirará en 15 minutos por razones de estricta seguridad escolar y resguardo integral infantil bajo protocolo COPPA.",
      submitBtn: "Enviar Enlace de Recuperación",
      // Panel lateral derecho
      panelBadge: "Montessori Digital AMI",
      panelTitle: "Protegiendo el Acceso a la Información de tu Pequeño 🛡️",
      panelDesc: "En Montekids resguardamos con los más altos estándares pedagógicos la bitácora sensorial, fotografías y evaluaciones del desarrollo de tu hijo.",
      card1Title: "Verificación de dos pasos activada",
      card1Desc: "Notificación inmediata al apoderado titular ante cualquier cambio de credenciales de acceso.",
      card2Title: "Soporte directo con secretaría",
      card2Desc: "Si perdiste acceso a tu correo, nuestro equipo valida tu identidad de manera presencial y segura.",
      card3Title: "Token encriptado de un solo uso",
      card3Desc: "Garantiza que la recuperación de clave solo sea procesada por el titular registrado.",
      noAccess: "¿Ya no tienes acceso a este buzón?",
      contactSchool: "Contactar a Secretaría Escolar",
      encryptionLabel: "Encriptación",
      sessionIdLabel: "ID de Sesión",
      successTitle: "¡Correo de recuperación enviado!",
      successInstructions: "Hemos enviado las instrucciones a",
      resendAvailableIn: "Reenviar correo disponible en",
      resendNow: "¡Reenviar correo de verificación!",
      verifyAnotherEmail: "Verificar otra dirección",
      goToLogin: "Ir a Iniciar Sesión",
    },
    parentDashboard: {
  metrics: {
    fineMotor: "Motricidad Fina",
    physicalArea: "Área Física",
    fineMotorBadge: "🌟 ¡Excelente en uso de pinza!",
    fineMotorDesc: "Logró encastres autónomos y trasvase de semillas con cuchara ergonómica sin dificultad.",
    language: "Lenguaje y Expresión",
    communicationArea: "Comunicación",
    languageBadge: "💬 Conoce 6 palabras nuevas",
    languageDesc: "Pronunciación fluida de fonemas /M/, /P/ y formulación de frases continuas de 4 elementos.",
    sensory: "Sensorial y Cognitivo",
    cognitionArea: "Cognición",
    sensoryBadge: "🧩 Avanzando en patrones",
    sensoryDesc: "Reconoce secuencias por color y disfruta la caja de texturas naturales con gran atención."
  },
  timeline: {
    headerTitle: "Bitácora del Día de Mateo",
    today: "Hoy, 28 de Octubre, 2026",
    inSession: "En Jornada Matutina",
    completedSuccess: "Completado con Éxito",
    completedAt: "Completado a las 11:15 AM",
    inProgress: "En curso actualmente",
    teacherName: "Docente Karina S.",
    act1Title: "Taller de Fonemas y Canciones",
    act1Area: "Área de Lenguaje",
    act1Time: "09:15 AM - 10:00 AM",
    act1Note: "“Mateo participó muy contento identificando la letra M en el vagón de rimas. Mostró mucho entusiasmo al cantar junto a Sofía y Lucas.”",
    act2Title: "Circuito de Texturas y Estimulación Olfativa",
    act2Area: "Área Sensorial",
    act2Time: "10:30 AM - 11:15 AM",
    act2Note: "“Exploró bandejas con lavanda y semillas sin ninguna resistencia táctil. Su tolerancia y calma fueron excelentes.”",
    act3Title: "Huerto Colaborativo y Merienda Saludable",
    act3Desc: "Horario: 11:45 AM - 12:30 PM • Cosecha guiada de tomates cherry y lavado de manos.",
    formTitle: "Enviar reporte o consulta a la guardería",
    formDesc: "Comunícate directamente con la Docente Karina o el equipo de recepción.",
    cat1: "Consulta de Salud",
    cat2: "Aviso de Horario / Retiro",
    cat3: "Consulta Pedagógica",
    placeholder: "Ej: Mañana retiro a las 11:30 AM por cita médica con el pediatra...",
    defaultMsg: "Mañana retiro a las 11:30 AM por cita médica con el pediatra.",
    sendBtn: "Enviar Reporte a Sala",
    successMsg: "¡Mensaje enviado a la Docente Karina! Se notificará su lectura en el receso."
  },
  sidebar: {
    achievementsTitle: "Logros Recientes",
    levelBadge: "Nivel Nido 2",
    badge1Title: "Pinza de Oro",
    badge1Desc: "Destreza motriz fina y autonomía",
    badge2Title: "Lector Estrella",
    badge2Desc: "Reconocimiento de 5 fonemas",
    badge3Title: "Amigo Colaborador",
    badge3Desc: "Ordenó y compartió material",
    viewAllBadges: "Ver todas las medallas (8) →",
    aiBadge: "💡 Sugerencia Semanal IA",
    aiTip: "“Tip para Mateo en casa: Para potenciar el 85% alcanzado en motricidad fina, refuercen juegos de encastre y amasado con plastilina durante 10 minutos antes de la cena.”",
    aiActionBtn: "Ver 3 Juegos para Casa 🏡",
    remindersTitle: "Próximos Recordatorios",
    rem1Title: "Reunión Trimestral de Familias",
    rem1Desc: "16:00 hrs • Sesión Virtual",
    rem2Title: "Día del Sombrero Loco & Huerta",
    rem2Desc: "Traer sombrero de reciclaje",
    syncCalendar: "Sincronizar con Google Calendar",
    teacherContactTitle: "Contacto de Sala",
    teacherRole: "Guía AMI Titular Aula Semillitas",
    teacherAvailability: "Disponible en receso (13:00 - 14:00)",
    whatsappBtn: "WhatsApp Institucional"
  },
  hero: {
    greeting: "¡Hola, Familia Quirós!",
    summaryStart: "Este es el resumen de",
    summaryMiddle: "hoy en el",
    presentBadge: "PRESENTE HOY",
    ageBadge: "3 Años cumplidos",
    classroomBadge: "Aula Semillitas",
    attendanceBadge: "Asistencia: 08:15 AM (Biométrico)",
    teacherBadge: "Guía: Docente Karina S.",
    sendNoteBtn: "+ ENVIAR NOTA A LA DOCENTE"
  },
  nav: {
    myChild: "Mi Hijo/a",
    reports: "Mis Comentarios/Reportes",
    calendar: "Calendario de Actividades",
    aiAssistant: "AI Asistente",
    userRole: "Mamá de Mateo"
  },
}
  },
  en: {
    nav: {
      home: 'Home',
      philosophy: 'Philosophy',
      classrooms: 'Classrooms',
      reviews: 'Reviews',
      contact: 'Location & Contact',
      aiAssistant: 'AI Assistant',
      login: 'Log In',
      backToHome: 'Back to Home',
      changeTextSize: 'Change text size',
      changeTheme: 'Toggle theme',
      colorblind: 'Color filter',
      language: 'Language'
    },
    hero: {
      badge: 'Early Stimulation Center',
      titleStart: 'The Place Where',
      wordLearn: 'Learning',
      and: 'and',
      wordGrow: 'Growing',
      isAn: 'is a',
      wordAdventure: 'Magical',
      wordMagical: 'Adventure',
      desc: 'Early stimulation, psychomotor development, and active learning for children aged 2 to 5 in a safe, nurturing environment guided by natural curiosity.',
      btnWhatsapp: 'Start Chat on WhatsApp',
      btnLocation: 'View Location',
      sensoryTitle: 'Active Sensory Session',
      sensoryDesc: 'Fine Motor Skills & Coordination',
      live: 'Live'
    },
    philosophy: {
      badge: 'AMI Philosophy & Methodology',
      title: 'Our Educational Philosophy and Methodology',
      desc: 'Three pillars designed to respect sensitive periods, innate curiosity, and comprehensive neurodevelopment.',
      c1Badge: '360° Development',
      c1Title: 'Comprehensive Early Stimulation 🧠',
      c1Desc: 'Integration of cognitive, motor, sensory, and socio-linguistic milestones through exploration with hands-on Montessori materials.',
      c1Footer: 'Sensory-Motor Circuits',
      c2Badge: 'Continuous Connection',
      c2Title: 'Family Support & Guidance 📱',
      c2Desc: 'Exclusive guardian access: real-time daily log, photo record of achievements, and direct teacher communication.',
      c2Footer: 'Montekids Family App',
      c3Badge: 'Pedagogical Innovation',
      c3Title: 'Continuous Tracking with AI 🌟',
      c3Desc: 'Synergy between expert educators and adaptive analytics to suggest personalized dynamics at each child’s pace.',
      c3Footer: 'Personalized Plans'
    },
    programs: {
      badge: 'Educational Programs',
      title: 'Our Classrooms and Developmental Levels',
      desc: 'Carefully prepared environments with child-scaled ergonomic furniture and self-correcting materials.',
      cycle: 'School Year 2027',
      openEnrollment: 'Enrollment Open',
      consultBtn: 'Check Availability',
      r1Age: '2 to 3 Years',
      r1Title: 'Little Seeds Room',
      r1Desc: 'Deep sensory stimulation, foundational communication structures, exploratory gross motor skills, and secure attachment.',
      r1Ratio: '1 Educator per 5 children',
      r1Cap: '10 children max per room',
      r1Sched: 'Morning (8:30 to 12:30)',
      r1Assigned: '80% Spots Filled',
      r1Free: '2 Spots Available',
      r2Age: '3 to 4 Years',
      r2Title: 'Explorers Room',
      r2Desc: 'Active language development, cooperative socialization, pre-logical thinking, and daily independence.',
      r2Ratio: '1 Educator per 7 children',
      r2Cap: '14 children max per room',
      r2Sched: 'Full or Half Day',
      r2Assigned: '65% Spots Filled',
      r2Free: '5 Spots Available',
      r3Age: '4 to 5 Years',
      r3Title: 'Creators Room',
      r3Desc: 'Sensory phonetic pre-literacy, refined fine motor skills, scientific projects, and playful discovery challenges.',
      r3Ratio: '1 Educator per 8 children',
      r3Cap: '16 children max per room',
      r3Sched: 'Full Day (8:30 to 16:30)',
      r3Assigned: '88% Spots Filled',
      r3Free: 'Last Spots',
      ratioLabel: 'Ratio:',
      capLabel: 'Capacity:',
      schedLabel: 'Schedule:'
    },
    testimonials: {
      badge: 'Community & Trust',
      title: 'Happy Families at Montekids',
      desc: 'Real testimonials from families who trust in our educational accompaniment.',
      t1Text: '“Outstanding care and methodology. Mateo has made huge strides in language, autonomy, and motor skills. Plus the web app keeps us informed about every daily milestone.”',
      t1Author: 'Valeria Quirós',
      t1Role: 'Mateo’s Mom (Explorers Room)',
      t2Text: '“The environment is affectionate and inspiring. The teachers are highly skilled, and the individual-paced approach makes a world of difference in Sofi’s self-confidence.”',
      t2Author: 'Carlos Mendoza',
      t2Role: 'Sofía’s Dad (Creators Room)',
      c1Val: '+150',
      c1Title: 'Happy Children',
      c1Desc: 'Actively guided',
      c2Val: '12',
      c2Title: 'Years of Experience',
      c2Desc: 'Cutting-edge education',
      c3Val: '100%',
      c3Title: 'Connected Families',
      c3Desc: 'In-app daily monitoring',
      c4Val: '5/5 ★',
      c4Title: 'Average Rating',
      c4Desc: 'Verified satisfaction'
    },
    location: {
      badge: 'Location & Direct Contact',
      title: 'Visit Us and Get in Touch',
      desc: 'Would you like to tour our facilities or inquire about admissions? Reach out directly or come visit us.',
      hoursBadge: 'Open 6:00 AM - 6:00 PM',
      hqTitle: 'Montekids Central Campus',
      address: '5A Ave, Puntarenas Province, El Roble, El Roble 2, 60101',
      scheduleLabel: 'Hours:',
      scheduleVal: 'Mon - Fri: 6:00 AM - 6:00 PM',
      phoneLabel: 'Phone:',
      emailLabel: 'Email:',
      btnWhatsapp: 'Start Chat on WhatsApp'
    },
    cta: {
      badge: 'Admissions 2027',
      title: 'Ready to empower your little one’s future?',
      desc: 'Limited spots for the 2027 school year. Schedule your in-person or virtual guided tour today and discover how we make every breakthrough memorable.',
      btnChat: 'Start Chat on WhatsApp',
      f1: 'Immediate response',
      f2: 'Personalized 40-min tour'
    },
    footer: {
      desc: 'Montessori Comprehensive Early Development & Stimulation Center. Cultivating wonder and natural autonomy from the very first steps.',
      certAmi: 'International AMI Certification',
      explore: 'Explore',
      linkPhil: 'Our philosophy',
      linkClass: 'Classrooms',
      linkRev: 'Reviews',
      linkLoc: 'Location & contact',
      contact: 'Contact',
      locPuntarenas: 'El Roble, Puntarenas',
      hours: 'Hours: Mon to Fri 06:00 - 18:00 hrs',
      copy: '© 2026 Montekids Early Childhood & Stimulation Center. All rights reserved.',
      privacy: 'Privacy Policy',
      protocol: 'Child Welfare Protocol'
    },
    auth: {
      tabLogin: 'Log In',
      tabRegister: 'Register',
      certBar: 'AMI Certified Platform • School-Grade Biometric Encryption',
      communityBar: 'Montekids Community • +1,400 Connected Families',
      montessoriBadge: 'Montessori Digital AMI',
      heroTitle: 'Guiding Your Child’s Growth 🌟',
      heroDesc: 'Access daily activity reports, sensory stimulation photo logs, classroom nursery rhymes, and direct messaging with guide educators.',
      heroF1: 'Real-time monitoring & live logs',
      heroF2: 'Motor & phonetic milestones tracking',
      heroF3: 'Secure portal for badges & achievements',
      trust1Title: 'Ironclad Privacy',
      trust1Desc: 'Strict COPPA & GDPR-K compliance',
      trust2Title: 'AMI Association',
      trust2Desc: 'Verified Montessori methodology',
      trust3Title: 'Family Support',
      trust3Desc: '24/7 pedagogical help desk',
      schoolCycle: 'School Year 2025 • Spring Term',
      loginWord1: 'Welcome',
      loginWord2: 'Back!',
      loginWord3: '',
      loginSubtitle: 'Log in to your account to continue real-time tracking of your little explorer and review their sensory logs.',
      googleAuth: 'Continue with Google Workspace for Education',
      orDivider: 'or with your credentials',
      emailLabel: 'Registered Email Address',
      emailPlaceholder: 'e.g. mateo.mom@email.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      forgotPassword: 'Forgot your password?',
      rememberMe: 'Remember on this device for 30 days',
      submitLogin: 'Enter Virtual Classroom',
      noAccountText: 'Don’t have a registered account for your child yet?',
      registerLink: 'Register Here ✨',
      regSchoolCycle: 'Family Enrollment • 2025 Cycle',
      regWord1: 'Create',
      regWord2: 'Your',
      regWord3: 'Family',
      regWord4: 'Account',
      regWord5: '',
      regSubtitle: 'Securely link direct access to the classroom and your child’s personalized log at Montekids.',
      regNameLabel: 'Guardian or Parent Full Name',
      regNamePlaceholder: 'e.g. Valeria Quirós Fernández',
      regEmailLabel: 'Contact Email Address',
      regEmailPlaceholder: 'your.email@example.com',
      regCodeLabel: 'Classroom / Student Code',
      regCodeBadge: 'Provided at Front Desk',
      regCodePlaceholder: 'e.g. MK-2025-EXPLO-88',
      createPassLabel: 'Create Secure Password',
      createPassPlaceholder: 'Minimum 8 characters',
      termsText1: 'I accept the',
      termsLink: 'Terms of Service',
      termsText2: 'and authorize processing under',
      privacyLink: 'AMI Policy',
      submitRegister: 'Create Family Account ✨',
      haveAccountText: 'Already have an active guardian account?',
      loginLink: 'Log In Here 🔒',
      passNone: 'No password',
      passWeak: 'Weak',
      passGood: 'Good',
      passStrong: 'Strong & Secure'
    },
    ai: {
      title: 'AI Virtual Assistant 🤖',
      online: 'Online and ready to help',
      welcome: "Hi! I\u2019m Montekids\u2019 AI assistant. How can I help you today? (e.g. schedules, location, or contact via WhatsApp)",
      reply: 'Great question! Our teaching team and available spots are ready. Would you like to set up a direct WhatsApp call?',
      placeholder: 'Type your question here...'
    },
    forgotPassword: {
      backToLogin: "Back to Login",
      title1: "Forgot",
      title2: "your",
      title3: "Password?",
      desc: "Enter the email address associated with your family or guardian account, and we will send you recovery instructions immediately.",
      emailLabel: "Registered Email Address",
      emailPlaceholder: "e.g. mateo.mom@email.com",
      expirationNotice: "The verification link will expire in 15 minutes due to strict school safety and child protection under COPPA protocol.",
      submitBtn: "Send Recovery Link",
      // Right side panel
      panelBadge: "Montessori Digital AMI",
      panelTitle: "Protecting Access to Your Child's Information 🛡️",
      panelDesc: "At Montekids, we safeguard your child's sensory logs, photos, and developmental assessments under the highest pedagogical standards.",
      card1Title: "Two-step verification active",
      card1Desc: "Immediate notification to primary guardian upon any access credential changes.",
      card2Title: "Direct support with office",
      card2Desc: "If you lost access to your email, our team verifies your identity securely in person.",
      card3Title: "Single-use encrypted token",
      card3Desc: "Ensures password recovery is only processed by the registered account owner.",
      noAccess: "No longer have access to this mailbox?",
      contactSchool: "Contact School Office",
      encryptionLabel: "Encryption",
      sessionIdLabel: "Session ID",
      successTitle: "Recovery email sent!",
      successInstructions: "We have sent the instructions to",
      resendAvailableIn: "Resend email available in",
      resendNow: "Resend verification email!",
      verifyAnotherEmail: "Verify another address",
      goToLogin: "Go to Login",
    },
    parentDashboard: {
  metrics: {
    fineMotor: "Fine Motor Skills",
    physicalArea: "Physical Area",
    fineMotorBadge: "🌟 Excellent pincer grasp!",
    fineMotorDesc: "Achieved independent fitting and seed transfer with an ergonomic spoon without difficulty.",
    language: "Language & Expression",
    communicationArea: "Communication",
    languageBadge: "💬 Knows 6 new words",
    languageDesc: "Fluent pronunciation of /M/ and /P/ phonemes and formulation of continuous 4-element phrases.",
    sensory: "Sensory & Cognitive",
    cognitionArea: "Cognition",
    sensoryBadge: "🧩 Progressing in patterns",
    sensoryDesc: "Recognizes color sequences and enjoys the natural texture box with great attention."
  },
  timeline: {
    headerTitle: "Mateo's Daily Log",
    today: "Today, October 28, 2026",
    inSession: "In Morning Session",
    completedSuccess: "Successfully Completed",
    completedAt: "Completed at 11:15 AM",
    inProgress: "Currently in progress",
    teacherName: "Teacher Karina S.",
    act1Title: "Phonemes & Songs Workshop",
    act1Area: "Language Area",
    act1Time: "09:15 AM - 10:00 AM",
    act1Note: "“Mateo happily participated in identifying the letter M in the rhyme wagon. Showed great enthusiasm singing with Sofía and Lucas.”",
    act2Title: "Texture Circuit & Olfactory Stimulation",
    act2Area: "Sensory Area",
    act2Time: "10:30 AM - 11:15 AM",
    act2Note: "“Explored trays with lavender and seeds without tactile resistance. His tolerance and composure were excellent.”",
    act3Title: "Collaborative Garden & Healthy Snack",
    act3Desc: "Schedule: 11:45 AM - 12:30 PM • Guided cherry tomato harvest and handwashing.",
    formTitle: "Send a report or query to daycare",
    formDesc: "Communicate directly with Teacher Karina or the front desk team.",
    cat1: "Health Query",
    cat2: "Schedule / Pickup Notice",
    cat3: "Pedagogical Query",
    placeholder: "E.g. Tomorrow pickup at 11:30 AM due to a pediatrician appointment...",
    defaultMsg: "Tomorrow pickup at 11:30 AM due to a pediatrician appointment.",
    sendBtn: "Send Report to Classroom",
    successMsg: "Message sent to Teacher Karina! Read receipt notification will be sent during break."
  },
  sidebar: {
    achievementsTitle: "Recent Achievements",
    levelBadge: "Nest Level 2",
    badge1Title: "Golden Pincer",
    badge1Desc: "Fine motor skill & autonomy",
    badge2Title: "Star Reader",
    badge2Desc: "Recognition of 5 phonemes",
    badge3Title: "Collaborative Friend",
    badge3Desc: "Organized and shared materials",
    viewAllBadges: "View all badges (8) →",
    aiBadge: "💡 Weekly AI Suggestion",
    aiTip: "“Tip for Mateo at home: To boost the 85% achieved in fine motor skills, reinforce fitting games and playdough kneading for 10 minutes before dinner.”",
    aiActionBtn: "View 3 Home Games 🏡",
    remindersTitle: "Upcoming Reminders",
    rem1Title: "Quarterly Family Meeting",
    rem1Desc: "04:00 PM • Virtual Session",
    rem2Title: "Crazy Hat & Garden Day",
    rem2Desc: "Bring recycled hat",
    syncCalendar: "Sync with Google Calendar",
    teacherContactTitle: "Classroom Contact",
    teacherRole: "Lead AMI Guide - Little Seeds Room",
    teacherAvailability: "Available during break (13:00 - 14:00)",
    whatsappBtn: "Institutional WhatsApp"
  },
  hero: {
    greeting: "Hello, Quirós Family!",
    summaryStart: "Here is the daily summary for",
    summaryMiddle: "today at",
    presentBadge: "PRESENT TODAY",
    ageBadge: "3 Years old",
    classroomBadge: "Little Seeds Room",
    attendanceBadge: "Attendance: 08:15 AM (Biometric)",
    teacherBadge: "Guide: Teacher Karina S.",
    sendNoteBtn: "+ SEND NOTE TO TEACHER"
  },
  nav: {
    myChild: "My Child",
    reports: "My Comments/Reports",
    calendar: "Activities Calendar",
    aiAssistant: "AI Assistant",
    userRole: "Mateo's Mom"
  },
}
  },
  zh: {
    nav: {
      home: '首页',
      philosophy: '教学理念',
      classrooms: '班级空间',
      reviews: '家长评价',
      contact: '位置与联系',
      aiAssistant: 'AI 助手',
      login: '登录',
      backToHome: '返回首页',
      changeTextSize: '更改字体大小',
      changeTheme: '切换主题',
      colorblind: '色盲模式',
      language: '语言'
    },
    hero: {
      badge: '早期潜能开发中心',
      titleStart: '在这里，让',
      wordLearn: '学习',
      and: '与',
      wordGrow: '成长',
      isAn: '成为一场',
      wordAdventure: '奇妙',
      wordMagical: '冒险',
      desc: '为2至5岁儿童提供早期启蒙、动作发育与主动学习，在安全温馨、由探索好奇心引领的环境中快乐成长。',
      btnWhatsapp: '通过 WhatsApp 咨询',
      btnLocation: '查看校区位置',
      sensoryTitle: '感官探索课程',
      sensoryDesc: '精细动作与身体协调',
      live: '进行中'
    },
    philosophy: {
      badge: 'AMI 国际蒙台梭利教学法',
      title: '我们的教育哲学与教学体系',
      desc: '尊重敏感期、启发天生好奇心并促进全面神经发育的三大教育基石。',
      c1Badge: '360° 全维发展',
      c1Title: '全面早期潜能开发 🧠',
      c1Desc: '借助蒙台梭利教具，将认知、动作、感官与社交语言发展有机融合。',
      c1Footer: '感觉统合探索',
      c2Badge: '家校紧密互联',
      c2Title: '家庭成长贴心陪伴 📱',
      c2Desc: '家长专属空间：实时动态记录、每日成就照片墙与导师直通互动。',
      c2Footer: 'Montekids 家长端 App',
      c3Badge: '智慧教育赋能',
      c3Title: 'AI 智能成长追踪 🌟',
      c3Desc: '资深教师团队与自适应数据分析协同，为每位孩子量身定制专属动态方案。',
      c3Footer: '定制化启蒙方案'
    },
    programs: {
      badge: '班级课程体系',
      title: '我们的特色教室与成长阶段',
      desc: '根据儿童人体工学精心配备适龄桌椅与自主纠错型蒙氏教具空间。',
      cycle: '2027 新学年',
      openEnrollment: '开放学位申请',
      consultBtn: '咨询学位',
      r1Age: '2 至 3 岁',
      r1Title: '萌芽班 (Semillitas)',
      r1Desc: '深度感官启蒙、早期语言萌发、探索性大动作训练与安全依恋建立。',
      r1Ratio: '师生比 1:5',
      r1Cap: '每班上限 10 名儿童',
      r1Sched: '上午半日 (8:30 - 12:30)',
      r1Assigned: '已录 80% 学位',
      r1Free: '仅剩 2 个名额',
      r2Age: '3 至 4 岁',
      r2Title: '探索班 (Exploradores)',
      r2Desc: '主动语言表达、协作性社交、前逻辑思维启蒙及日常生活自理能力。',
      r2Ratio: '师生比 1:7',
      r2Cap: '每班上限 14 名儿童',
      r2Sched: '全日制或半日制',
      r2Assigned: '已录 65% 学位',
      r2Free: '剩余 5 个名额',
      r3Age: '4 至 5 岁',
      r3Title: '创想班 (Creadores)',
      r3Desc: '多感官拼音读写准备、精细动作熟练、科学探究实验与启发式游戏挑战。',
      r3Ratio: '师生比 1:8',
      r3Cap: '每班上限 16 名儿童',
      r3Sched: '全日制 (8:30 - 16:30)',
      r3Assigned: '已录 88% 学位',
      r3Free: '即将满员',
      ratioLabel: '师资配置:',
      capLabel: '班级容量:',
      schedLabel: '作息时间:'
    },
    testimonials: {
      badge: '社群信赖与认可',
      title: 'Montekids 幸福家庭分享',
      desc: '来自信赖我们陪伴的真实家长心声。',
      t1Text: '“关怀非常细致，教学方法极佳。Mateo 在语言、独立性和运动方面进步飞速。而且家长平台每天都能清晰看到他的每一个微小突破。”',
      t1Author: 'Valeria Quirós',
      t1Role: 'Mateo 妈妈 (探索班)',
      t2Text: '“园所环境充满爱意与启迪。老师专业素养极高，因材施教的理念让 Sofi 充满了自信与安全感。”',
      t2Author: 'Carlos Mendoza',
      t2Role: 'Sofía 爸爸 (创想班)',
      c1Val: '+150',
      c1Title: '快乐儿童',
      c1Desc: '悉心温暖陪伴',
      c2Val: '12',
      c2Title: '年卓越办学',
      c2Desc: '国际前沿教育',
      c3Val: '100%',
      c3Title: '家庭连接率',
      c3Desc: 'App 实时动态',
      c4Val: '5/5 ★',
      c4Title: '综合评分',
      c4Desc: '权威家校满意度'
    },
    location: {
      badge: '校区地址与直达联系',
      title: '欢迎探校与垂询',
      desc: '想要实地参观校区或咨询学位？欢迎随时致电、留言或亲临校园。',
      hoursBadge: '服务时间：6:00 AM - 6:00 PM',
      hqTitle: 'Montekids 核心校区',
      address: '蓬塔雷纳斯省，埃尔罗布莱 5A 大道，60101',
      scheduleLabel: '开放时间:',
      scheduleVal: '周一至周五: 6:00 AM - 6:00 PM',
      phoneLabel: '联系电话:',
      emailLabel: '电子邮箱:',
      btnWhatsapp: '通过 WhatsApp 咨询'
    },
    cta: {
      badge: '2027 学位申请',
      title: '准备好开启孩子的美好未来了吗？',
      desc: '2027 学年学位有限。即刻预约线下探校或一对一线上咨询，让我们将每次探索都变成难忘的成长记忆。',
      btnChat: '通过 WhatsApp 咨询',
      f1: '即时响应',
      f2: '40分钟定制化探校体验'
    },
    footer: {
      desc: '蒙台梭利早期儿童成长与全面潜能开发中心。从人生的最初脚步起，守护天生好奇与自主。',
      certAmi: '国际 AMI 权威认证',
      explore: '探索发现',
      linkPhil: '教育哲学',
      linkClass: '班级空间',
      linkRev: '家长评价',
      linkLoc: '校区与联系',
      contact: '联系我们',
      locPuntarenas: '蓬塔雷纳斯，埃尔罗布莱',
      hours: '营业时间: 周一至周五 06:00 - 18:00',
      copy: '© 2026 Montekids 早期儿童与潜能开发中心。版权所有。',
      privacy: '隐私政策',
      protocol: '儿童关怀安全准则'
    },
    auth: {
      tabLogin: '登录',
      tabRegister: '注册账户',
      certBar: 'AMI 认证教育平台 • 校园级生物特征安全加密',
      communityBar: 'Montekids 社群 • 超 1,400 个家庭信赖互联',
      montessoriBadge: '蒙台梭利数字化教学体系',
      heroTitle: '全程护航孩子的每一步成长 🌟',
      heroDesc: '随时查看每日活动报告、感官探索精彩照片、课堂童谣音频，并与带班导师一对一即时交流。',
      heroF1: '实时动态成长记录',
      heroF2: '运动机能与语言里程碑跟踪',
      heroF3: '安全荣誉勋章与微奖励空间',
      trust1Title: '铜墙铁壁般的隐私保护',
      trust1Desc: '严格符合 COPPA 与 GDPR-K 儿童安全规范',
      trust2Title: '国际 AMI 协会',
      trust2Desc: '纯正蒙台梭利教学法验证',
      trust3Title: '全天候家庭支持',
      trust3Desc: '24/7 专业教育咨询帮助台',
      schoolCycle: '2025 学年 • 春季学期',
      loginWord1: '欢迎',
      loginWord2: '回来！',
      loginWord3: '',
      loginSubtitle: '登录您的账户，继续实时关注您的小探险家并查看他们的感官成长记录。',
      googleAuth: '使用 Google Workspace 校园账号登录',
      orDivider: '或使用邮箱密码登录',
      emailLabel: '注册家长 / 监护人邮箱',
      emailPlaceholder: '例如: mama.mateo@email.com',
      passwordLabel: '密码',
      passwordPlaceholder: '••••••••',
      forgotPassword: '忘记密码？',
      rememberMe: '在此设备上保持登录 30 天',
      submitLogin: '进入虚拟课堂',
      noAccountText: '还没有为您的小朋友注册账号？',
      registerLink: '在此注册 ✨',
      regSchoolCycle: '家庭注册入读 • 2025 学年',
      regWord1: '创建',
      regWord2: '您的',
      regWord3: '家庭',
      regWord4: '账户',
      regWord5: '',
      regSubtitle: '安全绑定课堂直通权限以及您孩子在 Montekids 的专属成长档案。',
      regNameLabel: '家长或监护人全名',
      regNamePlaceholder: '例如: Valeria Quirós Fernández',
      regEmailLabel: '常用联系邮箱',
      regEmailPlaceholder: 'your.email@example.com',
      regCodeLabel: '班级 / 学员认证码',
      regCodeBadge: '由前台教务提供',
      regCodePlaceholder: '例如: MK-2025-EXPLO-88',
      createPassLabel: '创建安全密码',
      createPassPlaceholder: '至少 8 位字符',
      termsText1: '我同意',
      termsLink: '服务条款',
      termsText2: '并授权依照',
      privacyLink: 'AMI 政策处理',
      submitRegister: '创建家庭账户 ✨',
      haveAccountText: '已经拥有活跃的监护人账户？',
      loginLink: '在此登录 🔒',
      passNone: '无密码',
      passWeak: '较弱',
      passGood: '良好',
      passStrong: '强且安全'
    },
    ai: {
      title: 'AI 智能助手 🤖',
      online: '在线随时为您解答',
      welcome: '您好！我是 Montekids AI 助手。请问有什么可以帮您？（例如：课程时间、校区位置或 WhatsApp 咨询）',
      reply: '感谢您的提问！我们的教学团队和学位咨询均已就绪。是否希望通过 WhatsApp 直接联系我们？',
      placeholder: '请输入您的问题...'
    },
    forgotPassword: {
      backToLogin: "返回登录",
      title1: "忘记",
      title2: "您的",
      title3: "密码？",
      desc: "请输入与您的家长或监护人账户关联的电子邮箱，我们将立即向您发送密码重置说明。",
      emailLabel: "已注册的电子邮箱",
      emailPlaceholder: "例如: mama.mateo@email.com",
      expirationNotice: "出于严格的校园安全及 COPPA 协议下的儿童保护规定，验证链接将在 15 分钟内失效。",
      submitBtn: "发送重置链接",
      panelBadge: "蒙台梭利数字化教学体系",
      panelTitle: "守护您孩子的个人信息安全 🛡️",
      panelDesc: "在 Montekids，我们依照最高标准的教育规范，妥善保护您孩子的感官记录、照片及成长评估。",
      card1Title: "已开启两步验证",
      card1Desc: "任何登录凭证的变更都将立即通知主监护人。",
      card2Title: "教务处直接支持",
      card2Desc: "如果您无法访问邮箱，我们的团队将通过线下安全验证您的身份。",
      card3Title: "一次性加密令牌",
      card3Desc: "确保密码重置仅由已注册的账户所有者操作。",
      noAccess: "无法访问此邮箱？",
      contactSchool: "联系教务处",
      encryptionLabel: "加密",
      sessionIdLabel: "会话 ID",
      successTitle: "找回密码邮件已发送！",
      successInstructions: "我们已将重置说明发送至：",
      resendAvailableIn: "可在...后重发邮件",
      resendNow: "重新发送验证邮件！",
      verifyAnotherEmail: "验证其他邮箱",
      goToLogin: "前往登录页面"
    },
    parentDashboard: {
      metrics: {
        fineMotor: "精细动作技能",
        physicalArea: "身体发展",
        fineMotorBadge: "🌟 抓握能力出色！",
        fineMotorDesc: "能够独立完成拼插，并熟练使用符合人体工程学的勺子转移种子。",
        language: "语言与表达",
        communicationArea: "沟通交流",
        languageBadge: "💬 掌握 6 个新词汇",
        languageDesc: "流利发音 /M/、/P/ 声母，并能说出由 4 个词组成的连贯句子。",
        sensory: "感官与认知",
        cognitionArea: "认知发展",
        sensoryBadge: "🧩 模式认知持续进步",
        sensoryDesc: "能按颜色识别序列，并非常专注地探索天然材质纹理盒。"
      },
      timeline: {
        headerTitle: "Mateo 的每日日志",
        today: "今天，2026年10月28日",
        inSession: "上午活动中",
        completedSuccess: "顺利完成",
        completedAt: "完成于 11:15 AM",
        inProgress: "进行中",
        teacherName: "Karina 老师",
        act1Title: "语音与童谣工作坊",
        act1Area: "语言领域",
        act1Time: "09:15 AM - 10:00 AM",
        act1Note: "“Mateo 非常高兴地参与了在押韵车厢中识别字母 M 的活动。和 Sofía、Lucas 一起唱歌时展现出了极大的热情。”",
        act2Title: "纹理环路与嗅觉刺激",
        act2Area: "感官领域",
        act2Time: "10:30 AM - 11:15 AM",
        act2Note: "“探索了装有薰衣草和种子的托盘，没有任何触觉排斥。他的耐受力和专注表现非常优秀。”",
        act3Title: "合作种植与健康加餐",
        act3Desc: "时间: 11:45 AM - 12:30 PM • 采摘樱桃番茄与洗手环节。",
        formTitle: "向托儿所发送报告或咨询",
        formDesc: "直接与 Karina 老师或前台团队沟通。",
        cat1: "健康咨询",
        cat2: "时间 / 接送通知",
        cat3: "教学咨询",
        placeholder: "例如：明天 11:30 AM 需要带孩子看儿科医生，提前接走...",
        defaultMsg: "明天 11:30 AM 因预约儿科医生需要提前接走孩子。",
        sendBtn: "发送至班级",
        successMsg: "消息已发送给 Karina 老师！将在休息时间通知阅读。"
      },
      sidebar: {
        achievementsTitle: "近期成就",
        levelBadge: "幼苗 2 级",
        badge1Title: "黄金抓握",
        badge1Desc: "精细动作与自主能力",
        badge2Title: "明星阅读者",
        badge2Desc: "识别 5 个发音",
        badge3Title: "合作小伙伴",
        badge3Desc: "整理并分享器材",
        viewAllBadges: "查看所有勋章 (8) →",
        aiBadge: "💡 AI 每周建议",
        aiTip: "“给 Mateo 家长的建议：为了巩固在精细动作上达到的 85% 进度，建议在晚餐前安排 10 分钟的拼插游戏或捏橡皮泥活动。”",
        aiActionBtn: "查看 3 个亲子互动游戏 🏡",
        remindersTitle: "近期提醒",
        rem1Title: "季度家长会",
        rem1Desc: "16:00 • 线上会议",
        rem2Title: "疯狂帽子与园艺日",
        rem2Desc: "请携带环保手工帽子",
        syncCalendar: "同步至谷歌日历",
        teacherContactTitle: "班级联系人",
        teacherRole: "Semillitas 班级 AMI 首席引导员",
        teacherAvailability: "休息时间在线 (13:00 - 14:00)",
        whatsappBtn: "官方 WhatsApp 联系"
      },
      hero: {
        greeting: "您好，Quirós 家长！",
        summaryStart: "这是",
        summaryMiddle: "今天在",
        summaryEnd: "的成长日报。",
        presentBadge: "今日出勤",
        ageBadge: "满 3 岁",
        classroomBadge: "萌芽班 (Semillitas)",
        attendanceBadge: "签到时间: 08:15 AM (人脸识别)",
        teacherBadge: "带班导师: Karina S.",
        sendNoteBtn: "+ 给老师发送留言"
      },
      nav: {
        myChild: "我的孩子",
        reports: "我的反馈/报告",
        calendar: "活动日程表",
        aiAssistant: "AI 助手",
        userRole: "Mateo 的妈妈"
      },
    }
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('montekids_language') || 'es';
  });

  useEffect(() => {
    localStorage.setItem('montekids_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (path, fallback = '') => {
    const keys = path.split('.');
    let current = translations[language];
    for (const key of keys) {
      if (!current || current[key] === undefined) {
        let fallbackVal = translations['es'];
        for (const fKey of keys) {
          if (!fallbackVal || fallbackVal[fKey] === undefined) return fallback;
          fallbackVal = fallbackVal[fKey];
        }
        return fallbackVal || fallback;
      }
      current = current[key];
    }
    return current || fallback;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'es',
      setLanguage: () => {},
      t: (path, fallback = '') => fallback
    };
  }
  return context;
}
