/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  es: {
    nav: {
      home: 'Inicio',
      philosophy: 'Filosofía',
      classrooms: 'Aulas',
      reviews: 'Opiniones',
      contact: 'Ubicación & Contacto',
      aiAssistant: 'Asistente IA',
      login: 'Iniciar Sesión',
      backToHome: 'Volver a Página Principal',
      changeTextSize: 'Cambiar tamaño de texto',
      changeTheme: 'Cambiar tema',
      colorblind: 'Daltonismo',
      language: 'Idioma'
    },
    hero: {
      badge: 'Centro de Estimulación Temprana',
      titleStart: 'El Lugar Donde',
      wordLearn: 'Aprender',
      and: 'y',
      wordGrow: 'Crecer',
      isAn: 'es una',
      wordAdventure: 'Aventura',
      wordMagical: 'Mágica',
      desc: 'Estimulación temprana, desarrollo psicomotor y aprendizaje activo para niños de 2 a 5 años en un entorno seguro, afectivo y guiado por la curiosidad natural.',
      btnWhatsapp: 'Iniciar Chat por WhatsApp',
      btnLocation: 'Ver Ubicación',
      sensoryTitle: 'Sesión Sensorial Activa',
      sensoryDesc: 'Motricidad Fina & Coordinación',
      live: 'En Vivo'
    },
    philosophy: {
      badge: 'Filosofía & Metodología AMI',
      title: 'Nuestra Filosofía y Metodología Pedagógica',
      desc: 'Tres pilares diseñados para respetar los periodos sensitivos, la curiosidad innata y el neurodesarrollo integral.',
      c1Badge: 'Desarrollo 360°',
      c1Title: 'Estimulación Temprana Integral 🧠',
      c1Desc: 'Integración de hitos cognitivos, motores, sensoriales y socio-lingüísticos mediante exploración con material concreto Montessori.',
      c1Footer: 'Circuitos Sensoriomotores',
      c2Badge: 'Conexión Continua',
      c2Title: 'Acompañamiento a Familias 📱',
      c2Desc: 'Acceso exclusivo para apoderados: bitácora diaria en tiempo real, registro fotográfico de logros y comunicación directa.',
      c2Footer: 'Montekids App Familiar',
      c3Badge: 'Innovación Pedagógica',
      c3Title: 'Seguimiento Continuo con IA 🌟',
      c3Desc: 'Sinergia entre educadoras de excelencia y análisis adaptativo para sugerir dinámicas personalizadas al ritmo de cada niño.',
      c3Footer: 'Planes Personalizados'
    },
    programs: {
      badge: 'Programas Educativos',
      title: 'Nuestras Aulas y Niveles de Desarrollo',
      desc: 'Espacios especialmente preparados con mobiliario ergonómico a escala infantil y materiales autocorrectivos.',
      cycle: 'Ciclo Escolar 2027',
      openEnrollment: 'Matrículas Abiertas',
      consultBtn: 'Consultar Cupo',
      r1Age: '2 a 3 Años',
      r1Title: 'Aula Semillitas',
      r1Desc: 'Estimulación sensorial profunda, primeras estructuras de comunicación, motricidad gruesa exploratoria y desapego seguro.',
      r1Ratio: '1 Educadora por 5 niños',
      r1Cap: '10 niños máximo por sala',
      r1Sched: 'Mañana (8:30 a 12:30)',
      r1Assigned: '80% Cupos Asignados',
      r1Free: '2 Lugares Libres',
      r2Age: '3 a 4 Años',
      r2Title: 'Aula Exploradores',
      r2Desc: 'Desarrollo de lenguaje activo, socialización cooperativa, pensamiento prelógico y conquista de la autonomía cotidiana.',
      r2Ratio: '1 Educadora por 7 niños',
      r2Cap: '14 niños máximo por sala',
      r2Sched: 'Completa o Media Jornada',
      r2Assigned: '65% Cupos Asignados',
      r2Free: '5 Lugares Libres',
      r3Age: '4 a 5 Años',
      r3Title: 'Aula Creadores',
      r3Desc: 'Iniciación a la pre-lectoescritura fonética sensorial, motricidad fina refinada, proyectos científicos y retos lúdicos.',
      r3Ratio: '1 Educadora por 8 niños',
      r3Cap: '16 niños máximo por sala',
      r3Sched: 'Completa (8:30 a 16:30)',
      r3Assigned: '88% Cupos Asignados',
      r3Free: 'Últimos Cupos',
      ratioLabel: 'Ratio:',
      capLabel: 'Capacidad:',
      schedLabel: 'Jornada:'
    },
    testimonials: {
      badge: 'Comunidad y Confianza',
      title: 'Familias Felices en Montekids',
      desc: 'Testimonios reales de familias que confían en nuestro acompañamiento.',
      t1Text: '“Excelente atención y metodología. Mateo ha avanzado muchísimo en su lenguaje, autonomía y motricidad. Además la plataforma web nos mantiene al tanto de cada hito diario.”',
      t1Author: 'Valeria Quirós',
      t1Role: 'Mamá de Mateo (Aula Exploradores)',
      t2Text: '“El ambiente es cariñoso y estimulante. Las maestras están altamente capacitadas y el enfoque en ritmo individual marca una gran diferencia en la seguridad de Sofi.”',
      t2Author: 'Carlos Mendoza',
      t2Role: 'Papá de Sofía (Aula Creadores)',
      c1Val: '+150',
      c1Title: 'Niños Felices',
      c1Desc: 'Acompañados activamente',
      c2Val: '12',
      c2Title: 'Años de Trayectoria',
      c2Desc: 'Educación de vanguardia',
      c3Val: '100%',
      c3Title: 'Familias Conectadas',
      c3Desc: 'Monitoreo en app',
      c4Val: '5/5 ★',
      c4Title: 'Valoración Promedio',
      c4Desc: 'Satisfacción verificada'
    },
    location: {
      badge: 'Ubicación & Contacto Directo',
      title: 'Visítanos y Ponte en Contacto',
      desc: '¿Quieres conocer nuestras instalaciones o consultar sobre cupos? Escríbenos directamente o visítanos.',
      hoursBadge: 'Atención de 6:00 AM - 6:00 PM',
      hqTitle: 'Sede Central Montekids',
      address: 'Av. 5A, Provincia de Puntarenas, El Roble, El Roble 2, 60101',
      scheduleLabel: 'Horario:',
      scheduleVal: 'Lun - Vie: 6:00 AM - 6:00 PM',
      phoneLabel: 'Teléfono:',
      emailLabel: 'Correo:',
      btnWhatsapp: 'Iniciar Chat por WhatsApp'
    },
    cta: {
      badge: 'Admisiones 2027',
      title: '¿Listo para impulsar el futuro de tu pequeño?',
      desc: 'Cupos limitados para el ciclo escolar 2027. Agenda hoy mismo tu visita guiada presencial o virtual y descubre cómo hacemos de cada descubrimiento una experiencia inolvidable.',
      btnChat: 'Iniciar Chat por WhatsApp',
      f1: 'Respuesta inmediata',
      f2: 'Recorrido personalizado de 40 min'
    },
    footer: {
      desc: 'Centro de Desarrollo Temprano y Estimulación Integral Montessori. Fomentando el asombro y la autonomía natural desde los primeros pasos.',
      certAmi: 'Certificación AMI Internacional',
      explore: 'Explora',
      linkPhil: 'Nuestra filosofía',
      linkClass: 'Aulas',
      linkRev: 'Opiniones',
      linkLoc: 'Ubicación y contacto',
      contact: 'Contacto',
      locPuntarenas: 'El Roble, Puntarenas',
      hours: 'Horario: Lun a Vie 06:00 - 6:00 hrs',
      copy: '© 2026 Montekids Early Childhood & Stimulation Center. Todos los derechos reservados.',
      privacy: 'Política de Privacidad',
      protocol: 'Protocolo de Bienestar Infantil'
    },
    auth: {
      tabLogin: 'Iniciar Sesión',
      tabRegister: 'Registrarse',
      certBar: 'Plataforma Certificada AMI • Encriptación Biométrica de Grado Escolar',
      communityBar: 'Comunidad Montekids • +1,400 Familias Conectadas',
      montessoriBadge: 'Montessori Digital AMI',
      heroTitle: 'Acompañando el Crecimiento de tu Hijo 🌟',
      heroDesc: 'Accede al reporte de actividades diarias, bitácora fotográfica de estimulación sensorial, canciones infantiles del aula y canal de comunicación directa con las maestras guías.',
      heroF1: 'Monitoreo y bitácora en tiempo real',
      heroF2: 'Registro de hitos motrices y fonéticos',
      heroF3: 'Portal seguro de logros y micro-premios',
      trust1Title: 'Privacidad Blindada',
      trust1Desc: 'Cumplimiento estricto COPPA y GDPR-K',
      trust2Title: 'Asociación AMI',
      trust2Desc: 'Metodología Montessori verificada',
      trust3Title: 'Soporte a Familias',
      trust3Desc: 'Mesa de ayuda pedagógica 24/7',
      schoolCycle: 'Ciclo Escolar 2025 • Trimestre de Primavera',
      loginWord1: '¡Hola',
      loginWord2: 'de',
      loginWord3: 'Nuevo!',
      loginSubtitle: 'Ingresa a tu cuenta para continuar con el seguimiento en vivo de tu pequeño explorador y revisar sus bitácoras sensoriales.',
      googleAuth: 'Continuar con Google Workspace Escolar',
      orDivider: 'o con tus credenciales',
      emailLabel: 'Correo Electrónico Registrado',
      emailPlaceholder: 'ej. mama.mateo@email.com',
      passwordLabel: 'Contraseña',
      passwordPlaceholder: '••••••••',
      forgotPassword: '¿Olvidaste tu contraseña?',
      rememberMe: 'Recordar en este dispositivo por 30 días',
      submitLogin: 'Ingresar al Aula Virtual',
      noAccountText: '¿Aún no tienes cuenta registrada para tu hijo?',
      registerLink: 'Registrarse Aquí ✨',
      regSchoolCycle: 'Inscripción Familiar • Ciclo 2025',
      regWord1: 'Crea',
      regWord2: 'tu',
      regWord3: 'Cuenta',
      regWord4: 'de',
      regWord5: 'Familia',
      regSubtitle: 'Vincula de forma segura el acceso directo al aula y a la bitácora personalizada de tu hijo en Montekids.',
      regNameLabel: 'Nombre Completo del Apoderado o Tutor',
      regNamePlaceholder: 'ej. Valeria Quirós Fernández',
      regEmailLabel: 'Correo Electrónico de Contacto',
      regEmailPlaceholder: 'tu.correo@ejemplo.com',
      regCodeLabel: 'Código de Aula / Alumno',
      regCodeBadge: 'Proporcionado en Recepción',
      regCodePlaceholder: 'ej. MK-2025-EXPLO-88',
      createPassLabel: 'Crear Contraseña Segura',
      createPassPlaceholder: 'Mínimo 8 caracteres',
      termsText1: 'Acepto los',
      termsLink: 'Términos de Servicio',
      termsText2: 'y autorizo el tratamiento bajo la',
      privacyLink: 'Política AMI',
      submitRegister: 'Crear Cuenta de Familia ✨',
      haveAccountText: '¿Ya tienes una cuenta de tutor activa?',
      loginLink: 'Iniciar Sesión Aquí 🔒',
      passNone: 'Sin contraseña',
      passWeak: 'Débil',
      passGood: 'Buena',
      passStrong: 'Fuerte y Segura'
    },
    ai: {
      title: 'Asistente Virtual IA 🤖',
      online: 'En línea para responder',
      welcome: '¡Hola! Soy el asistente de IA de Montekids. ¿En qué puedo ayudarte hoy? (ej. Horarios, ubicación, o contactar por WhatsApp)',
      reply: '¡Excelente consulta! Nuestro equipo pedagógico y las vacantes están disponibles. ¿Deseas coordinar un llamado directo por WhatsApp?',
      placeholder: 'Escribe tu consulta aquí...'
    }
  },
  en: {
    nav: {
      home: 'Home',
      philosophy: 'Philosophy',
      classrooms: 'Classrooms',
      reviews: 'Reviews',
      contact: 'Location & Contact',
      aiAssistant: 'AI Assistant',
      login: 'Log In',
      backToHome: 'Back to Home',
      changeTextSize: 'Change text size',
      changeTheme: 'Toggle theme',
      colorblind: 'Color filter',
      language: 'Language'
    },
    hero: {
      badge: 'Early Stimulation Center',
      titleStart: 'The Place Where',
      wordLearn: 'Learning',
      and: 'and',
      wordGrow: 'Growing',
      isAn: 'is a',
      wordAdventure: 'Magical',
      wordMagical: 'Adventure',
      desc: 'Early stimulation, psychomotor development, and active learning for children aged 2 to 5 in a safe, nurturing environment guided by natural curiosity.',
      btnWhatsapp: 'Start Chat on WhatsApp',
      btnLocation: 'View Location',
      sensoryTitle: 'Active Sensory Session',
      sensoryDesc: 'Fine Motor Skills & Coordination',
      live: 'Live'
    },
    philosophy: {
      badge: 'AMI Philosophy & Methodology',
      title: 'Our Educational Philosophy and Methodology',
      desc: 'Three pillars designed to respect sensitive periods, innate curiosity, and comprehensive neurodevelopment.',
      c1Badge: '360° Development',
      c1Title: 'Comprehensive Early Stimulation 🧠',
      c1Desc: 'Integration of cognitive, motor, sensory, and socio-linguistic milestones through exploration with hands-on Montessori materials.',
      c1Footer: 'Sensory-Motor Circuits',
      c2Badge: 'Continuous Connection',
      c2Title: 'Family Support & Guidance 📱',
      c2Desc: 'Exclusive guardian access: real-time daily log, photo record of achievements, and direct teacher communication.',
      c2Footer: 'Montekids Family App',
      c3Badge: 'Pedagogical Innovation',
      c3Title: 'Continuous Tracking with AI 🌟',
      c3Desc: 'Synergy between expert educators and adaptive analytics to suggest personalized dynamics at each child’s pace.',
      c3Footer: 'Personalized Plans'
    },
    programs: {
      badge: 'Educational Programs',
      title: 'Our Classrooms and Developmental Levels',
      desc: 'Carefully prepared environments with child-scaled ergonomic furniture and self-correcting materials.',
      cycle: 'School Year 2027',
      openEnrollment: 'Enrollment Open',
      consultBtn: 'Check Availability',
      r1Age: '2 to 3 Years',
      r1Title: 'Little Seeds Room',
      r1Desc: 'Deep sensory stimulation, foundational communication structures, exploratory gross motor skills, and secure attachment.',
      r1Ratio: '1 Educator per 5 children',
      r1Cap: '10 children max per room',
      r1Sched: 'Morning (8:30 to 12:30)',
      r1Assigned: '80% Spots Filled',
      r1Free: '2 Spots Available',
      r2Age: '3 to 4 Years',
      r2Title: 'Explorers Room',
      r2Desc: 'Active language development, cooperative socialization, pre-logical thinking, and daily independence.',
      r2Ratio: '1 Educator per 7 children',
      r2Cap: '14 children max per room',
      r2Sched: 'Full or Half Day',
      r2Assigned: '65% Spots Filled',
      r2Free: '5 Spots Available',
      r3Age: '4 to 5 Years',
      r3Title: 'Creators Room',
      r3Desc: 'Sensory phonetic pre-literacy, refined fine motor skills, scientific projects, and playful discovery challenges.',
      r3Ratio: '1 Educator per 8 children',
      r3Cap: '16 children max per room',
      r3Sched: 'Full Day (8:30 to 16:30)',
      r3Assigned: '88% Spots Filled',
      r3Free: 'Last Spots',
      ratioLabel: 'Ratio:',
      capLabel: 'Capacity:',
      schedLabel: 'Schedule:'
    },
    testimonials: {
      badge: 'Community & Trust',
      title: 'Happy Families at Montekids',
      desc: 'Real testimonials from families who trust in our educational accompaniment.',
      t1Text: '“Outstanding care and methodology. Mateo has made huge strides in language, autonomy, and motor skills. Plus the web app keeps us informed about every daily milestone.”',
      t1Author: 'Valeria Quirós',
      t1Role: 'Mateo’s Mom (Explorers Room)',
      t2Text: '“The environment is affectionate and inspiring. The teachers are highly skilled, and the individual-paced approach makes a world of difference in Sofi’s self-confidence.”',
      t2Author: 'Carlos Mendoza',
      t2Role: 'Sofía’s Dad (Creators Room)',
      c1Val: '+150',
      c1Title: 'Happy Children',
      c1Desc: 'Actively guided',
      c2Val: '12',
      c2Title: 'Years of Experience',
      c2Desc: 'Cutting-edge education',
      c3Val: '100%',
      c3Title: 'Connected Families',
      c3Desc: 'In-app daily monitoring',
      c4Val: '5/5 ★',
      c4Title: 'Average Rating',
      c4Desc: 'Verified satisfaction'
    },
    location: {
      badge: 'Location & Direct Contact',
      title: 'Visit Us and Get in Touch',
      desc: 'Would you like to tour our facilities or inquire about admissions? Reach out directly or come visit us.',
      hoursBadge: 'Open 6:00 AM - 6:00 PM',
      hqTitle: 'Montekids Central Campus',
      address: '5A Ave, Puntarenas Province, El Roble, El Roble 2, 60101',
      scheduleLabel: 'Hours:',
      scheduleVal: 'Mon - Fri: 6:00 AM - 6:00 PM',
      phoneLabel: 'Phone:',
      emailLabel: 'Email:',
      btnWhatsapp: 'Start Chat on WhatsApp'
    },
    cta: {
      badge: 'Admissions 2027',
      title: 'Ready to empower your little one’s future?',
      desc: 'Limited spots for the 2027 school year. Schedule your in-person or virtual guided tour today and discover how we make every breakthrough memorable.',
      btnChat: 'Start Chat on WhatsApp',
      f1: 'Immediate response',
      f2: 'Personalized 40-min tour'
    },
    footer: {
      desc: 'Montessori Comprehensive Early Development & Stimulation Center. Cultivating wonder and natural autonomy from the very first steps.',
      certAmi: 'International AMI Certification',
      explore: 'Explore',
      linkPhil: 'Our philosophy',
      linkClass: 'Classrooms',
      linkRev: 'Reviews',
      linkLoc: 'Location & contact',
      contact: 'Contact',
      locPuntarenas: 'El Roble, Puntarenas',
      hours: 'Hours: Mon to Fri 06:00 - 18:00 hrs',
      copy: '© 2026 Montekids Early Childhood & Stimulation Center. All rights reserved.',
      privacy: 'Privacy Policy',
      protocol: 'Child Welfare Protocol'
    },
    auth: {
      tabLogin: 'Log In',
      tabRegister: 'Register',
      certBar: 'AMI Certified Platform • School-Grade Biometric Encryption',
      communityBar: 'Montekids Community • +1,400 Connected Families',
      montessoriBadge: 'Montessori Digital AMI',
      heroTitle: 'Guiding Your Child’s Growth 🌟',
      heroDesc: 'Access daily activity reports, sensory stimulation photo logs, classroom nursery rhymes, and direct messaging with guide educators.',
      heroF1: 'Real-time monitoring & live logs',
      heroF2: 'Motor & phonetic milestones tracking',
      heroF3: 'Secure portal for badges & achievements',
      trust1Title: 'Ironclad Privacy',
      trust1Desc: 'Strict COPPA & GDPR-K compliance',
      trust2Title: 'AMI Association',
      trust2Desc: 'Verified Montessori methodology',
      trust3Title: 'Family Support',
      trust3Desc: '24/7 pedagogical help desk',
      schoolCycle: 'School Year 2025 • Spring Term',
      loginWord1: 'Welcome',
      loginWord2: 'Back!',
      loginWord3: '',
      loginSubtitle: 'Log in to your account to continue real-time tracking of your little explorer and review their sensory logs.',
      googleAuth: 'Continue with Google Workspace for Education',
      orDivider: 'or with your credentials',
      emailLabel: 'Registered Email Address',
      emailPlaceholder: 'e.g. mateo.mom@email.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      forgotPassword: 'Forgot your password?',
      rememberMe: 'Remember on this device for 30 days',
      submitLogin: 'Enter Virtual Classroom',
      noAccountText: 'Don’t have a registered account for your child yet?',
      registerLink: 'Register Here ✨',
      regSchoolCycle: 'Family Enrollment • 2025 Cycle',
      regWord1: 'Create',
      regWord2: 'Your',
      regWord3: 'Family',
      regWord4: 'Account',
      regWord5: '',
      regSubtitle: 'Securely link direct access to the classroom and your child’s personalized log at Montekids.',
      regNameLabel: 'Guardian or Parent Full Name',
      regNamePlaceholder: 'e.g. Valeria Quirós Fernández',
      regEmailLabel: 'Contact Email Address',
      regEmailPlaceholder: 'your.email@example.com',
      regCodeLabel: 'Classroom / Student Code',
      regCodeBadge: 'Provided at Front Desk',
      regCodePlaceholder: 'e.g. MK-2025-EXPLO-88',
      createPassLabel: 'Create Secure Password',
      createPassPlaceholder: 'Minimum 8 characters',
      termsText1: 'I accept the',
      termsLink: 'Terms of Service',
      termsText2: 'and authorize processing under',
      privacyLink: 'AMI Policy',
      submitRegister: 'Create Family Account ✨',
      haveAccountText: 'Already have an active guardian account?',
      loginLink: 'Log In Here 🔒',
      passNone: 'No password',
      passWeak: 'Weak',
      passGood: 'Good',
      passStrong: 'Strong & Secure'
    },
    ai: {
      title: 'AI Virtual Assistant 🤖',
      online: 'Online and ready to help',
      welcome: "Hi! I\u2019m Montekids\u2019 AI assistant. How can I help you today? (e.g. schedules, location, or contact via WhatsApp)",
      reply: 'Great question! Our teaching team and available spots are ready. Would you like to set up a direct WhatsApp call?',
      placeholder: 'Type your question here...'
    }
  },
  zh: {
    nav: {
      home: '首页',
      philosophy: '教学理念',
      classrooms: '班级空间',
      reviews: '家长评价',
      contact: '位置与联系',
      aiAssistant: 'AI 助手',
      login: '登录',
      backToHome: '返回首页',
      changeTextSize: '更改字体大小',
      changeTheme: '切换主题',
      colorblind: '色盲模式',
      language: '语言'
    },
    hero: {
      badge: '早期潜能开发中心',
      titleStart: '在这里，让',
      wordLearn: '学习',
      and: '与',
      wordGrow: '成长',
      isAn: '成为一场',
      wordAdventure: '奇妙',
      wordMagical: '冒险',
      desc: '为2至5岁儿童提供早期启蒙、动作发育与主动学习，在安全温馨、由探索好奇心引领的环境中快乐成长。',
      btnWhatsapp: '通过 WhatsApp 咨询',
      btnLocation: '查看校区位置',
      sensoryTitle: '感官探索课程',
      sensoryDesc: '精细动作与身体协调',
      live: '进行中'
    },
    philosophy: {
      badge: 'AMI 国际蒙台梭利教学法',
      title: '我们的教育哲学与教学体系',
      desc: '尊重敏感期、启发天生好奇心并促进全面神经发育的三大教育基石。',
      c1Badge: '360° 全维发展',
      c1Title: '全面早期潜能开发 🧠',
      c1Desc: '借助蒙台梭利教具，将认知、动作、感官与社交语言发展有机融合。',
      c1Footer: '感觉统合探索',
      c2Badge: '家校紧密互联',
      c2Title: '家庭成长贴心陪伴 📱',
      c2Desc: '家长专属空间：实时动态记录、每日成就照片墙与导师直通互动。',
      c2Footer: 'Montekids 家长端 App',
      c3Badge: '智慧教育赋能',
      c3Title: 'AI 智能成长追踪 🌟',
      c3Desc: '资深教师团队与自适应数据分析协同，为每位孩子量身定制专属动态方案。',
      c3Footer: '定制化启蒙方案'
    },
    programs: {
      badge: '班级课程体系',
      title: '我们的特色教室与成长阶段',
      desc: '根据儿童人体工学精心配备适龄桌椅与自主纠错型蒙氏教具空间。',
      cycle: '2027 新学年',
      openEnrollment: '开放学位申请',
      consultBtn: '咨询学位',
      r1Age: '2 至 3 岁',
      r1Title: '萌芽班 (Semillitas)',
      r1Desc: '深度感官启蒙、早期语言萌发、探索性大动作训练与安全依恋建立。',
      r1Ratio: '师生比 1:5',
      r1Cap: '每班上限 10 名儿童',
      r1Sched: '上午半日 (8:30 - 12:30)',
      r1Assigned: '已录 80% 学位',
      r1Free: '仅剩 2 个名额',
      r2Age: '3 至 4 岁',
      r2Title: '探索班 (Exploradores)',
      r2Desc: '主动语言表达、协作性社交、前逻辑思维启蒙及日常生活自理能力。',
      r2Ratio: '师生比 1:7',
      r2Cap: '每班上限 14 名儿童',
      r2Sched: '全日制或半日制',
      r2Assigned: '已录 65% 学位',
      r2Free: '剩余 5 个名额',
      r3Age: '4 至 5 岁',
      r3Title: '创想班 (Creadores)',
      r3Desc: '多感官拼音读写准备、精细动作熟练、科学探究实验与启发式游戏挑战。',
      r3Ratio: '师生比 1:8',
      r3Cap: '每班上限 16 名儿童',
      r3Sched: '全日制 (8:30 - 16:30)',
      r3Assigned: '已录 88% 学位',
      r3Free: '即将满员',
      ratioLabel: '师资配置:',
      capLabel: '班级容量:',
      schedLabel: '作息时间:'
    },
    testimonials: {
      badge: '社群信赖与认可',
      title: 'Montekids 幸福家庭分享',
      desc: '来自信赖我们陪伴的真实家长心声。',
      t1Text: '“关怀非常细致，教学方法极佳。Mateo 在语言、独立性和运动方面进步飞速。而且家长平台每天都能清晰看到他的每一个微小突破。”',
      t1Author: 'Valeria Quirós',
      t1Role: 'Mateo 妈妈 (探索班)',
      t2Text: '“园所环境充满爱意与启迪。老师专业素养极高，因材施教的理念让 Sofi 充满了自信与安全感。”',
      t2Author: 'Carlos Mendoza',
      t2Role: 'Sofía 爸爸 (创想班)',
      c1Val: '+150',
      c1Title: '快乐儿童',
      c1Desc: '悉心温暖陪伴',
      c2Val: '12',
      c2Title: '年卓越办学',
      c2Desc: '国际前沿教育',
      c3Val: '100%',
      c3Title: '家庭连接率',
      c3Desc: 'App 实时动态',
      c4Val: '5/5 ★',
      c4Title: '综合评分',
      c4Desc: '权威家校满意度'
    },
    location: {
      badge: '校区地址与直达联系',
      title: '欢迎探校与垂询',
      desc: '想要实地参观校区或咨询学位？欢迎随时致电、留言或亲临校园。',
      hoursBadge: '服务时间：6:00 AM - 6:00 PM',
      hqTitle: 'Montekids 核心校区',
      address: '蓬塔雷纳斯省，埃尔罗布莱 5A 大道，60101',
      scheduleLabel: '开放时间:',
      scheduleVal: '周一至周五: 6:00 AM - 6:00 PM',
      phoneLabel: '联系电话:',
      emailLabel: '电子邮箱:',
      btnWhatsapp: '通过 WhatsApp 咨询'
    },
    cta: {
      badge: '2027 学位申请',
      title: '准备好开启孩子的美好未来了吗？',
      desc: '2027 学年学位有限。即刻预约线下探校或一对一线上咨询，让我们将每次探索都变成难忘的成长记忆。',
      btnChat: '通过 WhatsApp 咨询',
      f1: '即时响应',
      f2: '40分钟定制化探校体验'
    },
    footer: {
      desc: '蒙台梭利早期儿童成长与全面潜能开发中心。从人生的最初脚步起，守护天生好奇与自主。',
      certAmi: '国际 AMI 权威认证',
      explore: '探索发现',
      linkPhil: '教育哲学',
      linkClass: '班级空间',
      linkRev: '家长评价',
      linkLoc: '校区与联系',
      contact: '联系我们',
      locPuntarenas: '蓬塔雷纳斯，埃尔罗布莱',
      hours: '营业时间: 周一至周五 06:00 - 18:00',
      copy: '© 2026 Montekids 早期儿童与潜能开发中心。版权所有。',
      privacy: '隐私政策',
      protocol: '儿童关怀安全准则'
    },
    auth: {
      tabLogin: '登录',
      tabRegister: '注册账户',
      certBar: 'AMI 认证教育平台 • 校园级生物特征安全加密',
      communityBar: 'Montekids 社群 • 超 1,400 个家庭信赖互联',
      montessoriBadge: '蒙台梭利数字化教学体系',
      heroTitle: '全程护航孩子的每一步成长 🌟',
      heroDesc: '随时查看每日活动报告、感官探索精彩照片、课堂童谣音频，并与带班导师一对一即时交流。',
      heroF1: '实时动态成长记录',
      heroF2: '运动机能与语言里程碑跟踪',
      heroF3: '安全荣誉勋章与微奖励空间',
      trust1Title: '铜墙铁壁般的隐私保护',
      trust1Desc: '严格符合 COPPA 与 GDPR-K 儿童安全规范',
      trust2Title: '国际 AMI 协会',
      trust2Desc: '纯正蒙台梭利教学法验证',
      trust3Title: '全天候家庭支持',
      trust3Desc: '24/7 专业教育咨询帮助台',
      schoolCycle: '2025 学年 • 春季学期',
      loginWord1: '欢迎',
      loginWord2: '回来！',
      loginWord3: '',
      loginSubtitle: '登录您的账户，继续实时关注您的小探险家并查看他们的感官成长记录。',
      googleAuth: '使用 Google Workspace 校园账号登录',
      orDivider: '或使用邮箱密码登录',
      emailLabel: '注册家长 / 监护人邮箱',
      emailPlaceholder: '例如: mama.mateo@email.com',
      passwordLabel: '密码',
      passwordPlaceholder: '••••••••',
      forgotPassword: '忘记密码？',
      rememberMe: '在此设备上保持登录 30 天',
      submitLogin: '进入虚拟课堂',
      noAccountText: '还没有为您的小朋友注册账号？',
      registerLink: '在此注册 ✨',
      regSchoolCycle: '家庭注册入读 • 2025 学年',
      regWord1: '创建',
      regWord2: '您的',
      regWord3: '家庭',
      regWord4: '账户',
      regWord5: '',
      regSubtitle: '安全绑定课堂直通权限以及您孩子在 Montekids 的专属成长档案。',
      regNameLabel: '家长或监护人全名',
      regNamePlaceholder: '例如: Valeria Quirós Fernández',
      regEmailLabel: '常用联系邮箱',
      regEmailPlaceholder: 'your.email@example.com',
      regCodeLabel: '班级 / 学员认证码',
      regCodeBadge: '由前台教务提供',
      regCodePlaceholder: '例如: MK-2025-EXPLO-88',
      createPassLabel: '创建安全密码',
      createPassPlaceholder: '至少 8 位字符',
      termsText1: '我同意',
      termsLink: '服务条款',
      termsText2: '并授权依照',
      privacyLink: 'AMI 政策处理',
      submitRegister: '创建家庭账户 ✨',
      haveAccountText: '已经拥有活跃的监护人账户？',
      loginLink: '在此登录 🔒',
      passNone: '无密码',
      passWeak: '较弱',
      passGood: '良好',
      passStrong: '强且安全'
    },
    ai: {
      title: 'AI 智能助手 🤖',
      online: '在线随时为您解答',
      welcome: '您好！我是 Montekids AI 助手。请问有什么可以帮您？（例如：课程时间、校区位置或 WhatsApp 咨询）',
      reply: '感谢您的提问！我们的教学团队和学位咨询均已就绪。是否希望通过 WhatsApp 直接联系我们？',
      placeholder: '请输入您的问题...'
    }
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('montekids_language') || 'es';
  });

  useEffect(() => {
    localStorage.setItem('montekids_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (path, fallback = '') => {
    const keys = path.split('.');
    let current = translations[language];
    for (const key of keys) {
      if (!current || current[key] === undefined) {
        let fallbackVal = translations['es'];
        for (const fKey of keys) {
          if (!fallbackVal || fallbackVal[fKey] === undefined) return fallback;
          fallbackVal = fallbackVal[fKey];
        }
        return fallbackVal || fallback;
      }
      current = current[key];
    }
    return current || fallback;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'es',
      setLanguage: () => {},
      t: (path, fallback = '') => fallback
    };
  }
  return context;
}
