/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  es: {
    nav: {
      home: 'Inicio',
      philosophy: 'Filosofía',
      classrooms: 'Aulas',
      reviews: 'Opiniones',
      contact: 'Ubicación & Contacto',
      aiAssistant: 'Asistente IA',
      login: 'Iniciar Sesión',
      backToHome: 'Volver a Página Principal',
      changeTextSize: 'Cambiar tamaño de texto',
      changeTheme: 'Cambiar tema',
      colorblind: 'Daltonismo',
      language: 'Idioma'
    },
    cancionesPage: {
      badgeSection: 'RINCÓN RÍTMICO',
      badgeCategory: 'Videos Musicales Educativos',
      title: 'Canciones Infantiles Animadas',
      playingBadge: 'REPRODUCIENDO VIDEO',
      starsReward: '+5 Estrellas al cantar completa',
      playVideo: 'Reproducir Video',
      pauseVideo: 'Pausar Video',
      restartVideo: 'Reiniciar',
      speedLabel: 'VELOCIDAD:',
      speedSlow: '0.8x Lento',
      speedNormal: '1.0x Normal',
      speedFast: '1.2x Rápido',
      catalogTitle: '¡Elige tu Canción Favorita!',
      seeAll: 'Ver todas',
      dailyMissionTitle: 'MISIÓN DIARIA • OYENTE ATENTO',
      dailyMissionLevel: 'Nivel Explorador',
      dailyMissionBannerTitle: '¡Canta y escucha canciones para ganar más estrellitas doradas!',
      dailyMissionBannerDesc: 'Cada canción reproducida ayuda al explorador a asociar sonidos mientras se divierte con los videos de La Gallinita Pintadita.',
      goalOfDay: 'Meta del Día',
      remainingSongs: '¡Faltan canciones!',
      bonusReward: '+10 ★ Bonus'
    },
    hero: {
      badge: 'Centro de Estimulación Temprana',
      titleStart: 'El Lugar Donde',
      wordLearn: 'Aprender',
      and: 'y',
      wordGrow: 'Crecer',
      isAn: 'es una',
      wordAdventure: 'Aventura',
      wordMagical: 'Mágica',
      desc: 'Estimulación temprana, desarrollo psicomotor y aprendizaje activo para bebés y niños en un entorno seguro, afectivo y guiado por la curiosidad natural.',
      btnWhatsapp: 'Iniciar Chat por WhatsApp',
      btnLocation: 'Ver Ubicación',
      sensoryTitle: 'Sesión Sensorial Activa',
      sensoryDesc: 'Motricidad Fina & Coordinación',
      live: 'En Vivo'
    },
    philosophy: {
      badge: 'Filosofía & Metodología AMI',
      title: 'Nuestra Filosofía y Metodología Pedagógica',
      desc: 'Tres pilares diseñados para respetar los periodos sensitivos, la curiosidad innata y el neurodesarrollo integral.',
      c1Badge: 'Desarrollo 360°',
      c1Title: 'Estimulación Temprana Integral 🧠',
      c1Desc: 'Integración de hitos cognitivos, motores, sensoriales y socio-lingüísticos mediante exploración con material concreto Montessori.',
      c1Footer: 'Circuitos Sensoriomotores',
      c2Badge: 'Conexión Continua',
      c2Title: 'Acompañamiento a Familias 📱',
      c2Desc: 'Acceso exclusivo para apoderados: bitácora diaria en tiempo real, registro fotográfico de logros y comunicación directa.',
      c2Footer: 'Montekids App Familiar',
      c3Badge: 'Innovación Pedagógica',
      c3Title: 'Seguimiento Continuo con IA 🌟',
      c3Desc: 'Sinergia entre educadoras de excelencia y análisis adaptativo para sugerir dinámicas personalizadas al ritmo de cada niño.',
      c3Footer: 'Planes Personalizados'
    },
    programs: {
      badge: 'Programas Educativos',
      title: 'Nuestras Aulas y Niveles de Desarrollo',
      desc: 'Espacios especialmente preparados con mobiliario ergonómico a escala infantil y materiales autocorrectivos.',
      cycle: 'Ciclo Escolar 2027',
      openEnrollment: 'Matrículas Abiertas',
      consultBtn: 'Consultar Cupo',
      r1Age: '2 a 3 Años',
      r1Title: 'Aula Semillitas',
      r1Desc: 'Estimulación sensorial profunda, primeras estructuras de comunicación, motricidad gruesa exploratoria y desapego seguro.',
      r1Ratio: '1 Educadora por 5 niños',
      r1Cap: '10 niños máximo por sala',
      r1Sched: 'Mañana (8:30 a 12:30)',
      r1Assigned: '80% Cupos Asignados',
      r1Free: '2 Lugares Libres',
      r2Age: '3 a 4 Años',
      r2Title: 'Aula Exploradores',
      r2Desc: 'Desarrollo de lenguaje activo, socialización cooperativa, pensamiento prelógico y conquista de la autonomía cotidiana.',
      r2Ratio: '1 Educadora por 7 niños',
      r2Cap: '14 niños máximo por sala',
      r2Sched: 'Completa o Media Jornada',
      r2Assigned: '65% Cupos Asignados',
      r2Free: '5 Lugares Libres',
      r3Age: '4 a 5 Años',
      r3Title: 'Aula Creadores',
      r3Desc: 'Iniciación a la pre-lectoescritura fonética sensorial, motricidad fina refinada, proyectos científicos y retos lúdicos.',
      r3Ratio: '1 Educadora por 8 niños',
      r3Cap: '16 niños máximo por sala',
      r3Sched: 'Completa (8:30 a 16:30)',
      r3Assigned: '88% Cupos Asignados',
      r3Free: 'Últimos Cupos',
      ratioLabel: 'Ratio:',
      capLabel: 'Capacidad:',
      schedLabel: 'Jornada:'
    },
    IMAS: {
      badge: 'Beneficio IMAS',
      title: '¿Tu hijo/a cuenta con beneficio IMAS?',
      desc: 'Si actualmente tu hijo asiste a otra guardería, puedes solicitar un traslado hacia MONTEKIDS. Nuestro equipo te orienta durante todo el proceso.',
      cycle: 'Ciclo Escolar 2027',
      openEnrollment: 'Matrículas Abiertas',
      consultBtn: 'Consultar Cupo',
      r1Age: 'Paso 1',
      r1Title: 'Completa el formulario de atención en línea del IMAS con tus datos personales, tu número de cédula y los datos del menor.',
      r1Desc: '',
      r1Ratio: '',
      r1Cap: '',
      r1Sched: '',
      r1Assigned: '',
      r1Free: '2 Lugares Libres',
      r2Age: 'Paso 2',
      r2Title: 'Especifica en la sección de detalles o notas que estás solicitando un traslado de centro de Cuidado y Desarrollo Infantil (CECUDI) o Red de Cuido, indicando la razón del cambio y el nuevo centro de interés.',
      r2Desc: '',
      r2Ratio: '',
      r2Cap: '',
      r2Sched: '',
      r2Assigned: '65% Cupos Asignados',
      r2Free: '5 Lugares Libres',
      r3Age: 'Paso 3',
      r3Title: 'Envía la solicitud y espera a que un trabajador social se comunique contigo para validar el cambio y verificar los espacios en la nueva ubicación.',
      r3Desc: '',
      r3Ratio: '',
      r3Cap: '',
      r3Sched: '',
      r3Assigned: '',
      r3Free: 'Últimos Cupos',
      ratioLabel: 'Ratio:',
      capLabel: 'Capacidad:',
      schedLabel: 'Jornada:'
    },
    testimonials: {
      badge: 'Comunidad y Confianza',
      title: 'Familias Felices en Montekids',
      desc: 'Testimonios reales de familias que confían en nuestro acompañamiento.',
      t1Text: '“Excelente atención y metodología. Mateo ha avanzado muchísimo en su lenguaje, autonomía y motricidad. Además la plataforma web nos mantiene al tanto de cada hito diario.”',
      t1Author: 'Valeria Quirós',
      t1Role: 'Mamá de Mateo (Aula Exploradores)',
      t2Text: '“El ambiente es cariñoso y estimulante. Las maestras están altamente capacitadas y el enfoque en ritmo individual marca una gran diferencia en la seguridad de Sofi.”',
      t2Author: 'Carlos Mendoza',
      t2Role: 'Papá de Sofía (Aula Creadores)',
      c1Val: '+150',
      c1Title: 'Niños Felices',
      c1Desc: 'Acompañados activamente',
      c2Val: '12',
      c2Title: 'Años de Trayectoria',
      c2Desc: 'Educación de vanguardia',
      c3Val: '100%',
      c3Title: 'Familias Conectadas',
      c3Desc: 'Monitoreo en app',
      c4Val: '5/5 ★',
      c4Title: 'Valoración Promedio',
      c4Desc: 'Satisfacción verificada'
    },
    location: {
      badge: 'Ubicación & Contacto Directo',
      title: 'Visítanos y Ponte en Contacto',
      desc: '¿Quieres conocer nuestras instalaciones o consultar sobre cupos? Escríbenos directamente o visítanos.',
      hoursBadge: 'Atención de 6:00 AM - 6:00 PM',
      hqTitle: 'Sede Central Montekids',
      address: 'Av. 5A, Provincia de Puntarenas, El Roble, El Roble 2, 60101',
      scheduleLabel: 'Horario:',
      scheduleVal: 'Lun - Vie: 6:00 AM - 6:00 PM',
      phoneLabel: 'Teléfono:',
      emailLabel: 'Correo:',
      btnWhatsapp: 'Iniciar Chat por WhatsApp'
    },
    cta: {
      badge: 'Admisiones 2027',
      title: '¿Listo para impulsar el futuro de tu pequeño?',
      desc: 'Cupos limitados para el ciclo escolar 2027. Agenda hoy mismo tu visita guiada presencial o virtual y descubre cómo hacemos de cada descubrimiento una experiencia inolvidable.',
      btnChat: 'Iniciar Chat por WhatsApp',
      f1: 'Respuesta inmediata',
      f2: 'Recorrido personalizado de 40 min'
    },
    footer: {
      desc: 'Centro de Desarrollo Temprano y Estimulación Integral Montessori. Fomentando el asombro y la autonomía natural desde los primeros pasos.',
      certAmi: 'Certificación AMI Internacional',
      explore: 'Explora',
      linkPhil: 'Nuestra filosofía',
      linkClass: 'Aulas',
      linkRev: 'Opiniones',
      linkLoc: 'Ubicación y contacto',
      contact: 'Contacto',
      locPuntarenas: 'El Roble, Puntarenas',
      hours: 'Horario: Lun a Vie 06:00 - 6:00 hrs',
      copy: '© 2026 Montekids Early Childhood & Stimulation Center. Todos los derechos reservados.',
      privacy: 'Política de Privacidad',
      protocol: 'Protocolo de Bienestar Infantil'
    },
    auth: {
      tabLogin: 'Iniciar Sesión',
      tabRegister: 'Registrarse',
      certBar: 'Plataforma Certificada AMI • Encriptación Biométrica de Grado Escolar',
      communityBar: 'Comunidad Montekids • +1,400 Familias Conectadas',
      montessoriBadge: 'Montessori Digital AMI',
      heroTitle: 'Acompañando el Crecimiento de tu Hijo 🌟',
      heroDesc: 'Accede al reporte de actividades diarias, bitácora fotográfica de estimulación sensorial, canciones infantiles del aula y canal de comunicación directa con las maestras guías.',
      heroF1: 'Monitoreo y bitácora en tiempo real',
      heroF2: 'Registro de hitos motrices y fonéticos',
      heroF3: 'Portal seguro de logros y micro-premios',
      trust1Title: 'Privacidad Blindada',
      trust1Desc: 'Cumplimiento estricto COPPA y GDPR-K',
      trust2Title: 'Asociación AMI',
      trust2Desc: 'Metodología Montessori verificada',
      trust3Title: 'Soporte a Familias',
      trust3Desc: 'Mesa de ayuda pedagógica 24/7',
      schoolCycle: 'Ciclo Escolar 2025 • Trimestre de Primavera',
      loginWord1: '¡Hola',
      loginWord2: 'de',
      loginWord3: 'Nuevo!',
      loginSubtitle: 'Ingresa a tu cuenta para continuar con el seguimiento en vivo de tu pequeño explorador y revisar sus bitácoras sensoriales.',
      googleAuth: 'Continuar con Google Workspace Escolar',
      orDivider: 'o con tus credenciales',
      emailLabel: 'Correo Electrónico Registrado',
      emailPlaceholder: 'ej. mama.mateo@email.com',
      passwordLabel: 'Contraseña',
      passwordPlaceholder: '••••••••',
      forgotPassword: '¿Olvidaste tu contraseña?',
      rememberMe: 'Recordar en este dispositivo por 30 días',
      submitLogin: 'Ingresar al Aula Virtual',
      noAccountText: '¿Aún no tienes cuenta registrada para tu hijo?',
      registerLink: 'Registrarse Aquí ✨',
      regSchoolCycle: 'Inscripción Familiar • Ciclo 2025',
      regWord1: 'Crea',
      regWord2: 'tu',
      regWord3: 'Cuenta',
      regWord4: 'de',
      regWord5: 'Familia',
      regSubtitle: 'Vincula de forma segura el acceso directo al aula y a la bitácora personalizada de tu hijo en Montekids.',
      regNameLabel: 'Nombre Completo del Apoderado o Tutor',
      regNamePlaceholder: 'ej. Valeria Quirós Fernández',
      regEmailLabel: 'Correo Electrónico de Contacto',
      regEmailPlaceholder: 'tu.correo@ejemplo.com',
      regCodeLabel: 'Código de Aula / Alumno',
      regCodeBadge: 'Proporcionado en Recepción',
      regCodePlaceholder: 'ej. MK-2025-EXPLO-88',
      createPassLabel: 'Crear Contraseña Segura',
      createPassPlaceholder: 'Mínimo 8 caracteres',
      termsText1: 'Acepto los',
      termsLink: 'Términos de Servicio',
      termsText2: 'y autorizo el tratamiento bajo la',
      privacyLink: 'Política AMI',
      submitRegister: 'Crear Cuenta de Familia ✨',
      haveAccountText: '¿Ya tienes una cuenta de tutor activa?',
      loginLink: 'Iniciar Sesión Aquí 🔒',
      passNone: 'Sin contraseña',
      passWeak: 'Débil',
      passGood: 'Buena',
      passStrong: 'Fuerte y Segura',
      invalidCredentials: "Correo o contraseña incorrectos. Por favor, verifica tus datos.",
      connectionError: "No se pudo conectar con el servidor de autenticación.",
      loggingIn: "Iniciando sesión...",
      loginButton: "Iniciar Sesión",
    },
    ai: {
      title: 'Asistente Virtual IA 🤖',
      online: 'En línea para responder',
      welcome: '¡Hola! Soy el asistente de IA de Montekids. ¿En qué puedo ayudarte hoy? (ej. Horarios, ubicación, o contactar por WhatsApp)',
      reply: '¡Excelente consulta! Nuestro equipo pedagógico y las vacantes están disponibles. ¿Deseas coordinar un llamado directo por WhatsApp?',
      placeholder: 'Escribe tu consulta aquí...'
    },
    forgotPassword: {
      backToLogin: "Volver al Login",
      title1: "¿Olvidaste",
      title2: "tu",
      title3: "Contraseña?",
      desc: "Ingresa el correo electrónico asociado a tu cuenta de familiar o tutor y te enviaremos las instrucciones de restablecimiento de forma inmediata.",
      emailLabel: "Correo Electrónico Registrado",
      emailPlaceholder: "ej. mama.mateo@email.com",
      expirationNotice: "El enlace de verificación expirará en 15 minutos por razones de estricta seguridad escolar y resguardo integral infantil bajo protocolo COPPA.",
      submitBtn: "Enviar Enlace de Recuperación",
      // Nuevos elementos y estados
      viewMode: "Vista:",
      formView: "Formulario",
      sentView: "Enviado",
      errorCode: "El código de verificación es incorrecto.",
      panelBadge: "Montessori Digital AMI",
      panelTitle: "Protegiendo el Acceso a la Información de tu Pequeño 🛡️",
      panelDesc: "En Montekids resguardamos con los más altos estándares pedagógicos la bitácora sensorial, fotografías y evaluaciones del desarrollo de tu hijo.",
      card1Title: "Verificación de dos pasos activada",
      card1Desc: "Notificación inmediata al apoderado titular ante cualquier cambio de credenciales de acceso.",
      card2Title: "Soporte directo con secretaría",
      card2Desc: "Si perdiste acceso a tu correo, nuestro equipo valida tu identidad de manera presencial y segura.",
      card3Title: "Token encriptado de un solo uso",
      card3Desc: "Garantiza que la recuperación de clave solo sea procesada por el titular registrado.",
      noAccess: "¿Ya no tienes acceso a este buzón?",
      contactSchool: "Contactar a Secretaría Escolar",
      encryptionLabel: "Encriptación",
      sessionIdLabel: "ID de Sesión",
      successTitle: "¡Correo de recuperación enviado!",
      successInstructions: "Hemos enviado las instrucciones a",
      resendAvailableIn: "Reenviar correo disponible en",
      resendNow: "¡Reenviar correo de verificación!",
      verifyAnotherEmail: "Verificar otra dirección",
      goToLogin: "Ir a Iniciar Sesión",
      validateAndLogin: "Validar e Iniciar Sesión",
      attemptsUsed: "Intentos usados",
      incompleteCodeError: "Por favor, ingresa los 6 dígitos completos del código de verificación.",
    },
    parentDashboard: {
      header: {
        badge: "Panel de Seguimiento Integral",
        title1: "Bitácora",
        title2: "y",
        title3: "Progreso",
        title4: "Familiar",
        subtitle: "Supervisión en tiempo real del desarrollo sensorial, cognitivo y actividades de",
        reportsBtn: "Mis Reportes & Notas"
      },
      metrics: {
    fineMotor: "Motricidad Fina",
    physicalArea: "Área Física",
    fineMotorBadge: "🌟 ¡Excelente en uso de pinza!",
    fineMotorDesc: "Logró encastres autónomos y trasvase de semillas con cuchara ergonómica sin dificultad.",
    language: "Lenguaje y Expresión",
    communicationArea: "Comunicación",
    languageBadge: "💬 Conoce 6 palabras nuevas",
    languageDesc: "Pronunciación fluida de fonemas /M/, /P/ y formulación de frases continuas de 4 elementos.",
    sensory: "Sensorial y Cognitivo",
    cognitionArea: "Cognición",
    sensoryBadge: "🧩 Avanzando en patrones",
    sensoryDesc: "Reconoce secuencias por color y disfruta la caja de texturas naturales con gran atención."
  },
  timeline: {
    headerTitle: "Bitácora del Día de Mateo",
    today: "Hoy, 28 de Octubre, 2026",
    inSession: "En Jornada Matutina",
    completedSuccess: "Completado con Éxito",
    completedAt: "Completado a las 11:15 AM",
    inProgress: "En curso actualmente",
    teacherName: "Docente Karina S.",
    act1Title: "Taller de Fonemas y Canciones",
    act1Area: "Área de Lenguaje",
    act1Time: "09:15 AM - 10:00 AM",
    act1Note: "“Mateo participó muy contento identificando la letra M en el vagón de rimas. Mostró mucho entusiasmo al cantar junto a Sofía y Lucas.”",
    act2Title: "Circuito de Texturas y Estimulación Olfativa",
    act2Area: "Área Sensorial",
    act2Time: "10:30 AM - 11:15 AM",
    act2Note: "“Exploró bandejas con lavanda y semillas sin ninguna resistencia táctil. Su tolerancia y calma fueron excelentes.”",
    act3Title: "Huerto Colaborativo y Merienda Saludable",
    act3Desc: "Horario: 11:45 AM - 12:30 PM • Cosecha guiada de tomates cherry y lavado de manos.",
    formTitle: "Enviar reporte o consulta a la guardería",
    formDesc: "Comunícate directamente con la Docente Karina o el equipo de recepción.",
    cat1: "Consulta de Salud",
    cat2: "Aviso de Horario / Retiro",
    cat3: "Consulta Pedagógica",
    placeholder: "Ej: Mañana retiro a las 11:30 AM por cita médica con el pediatra...",
    defaultMsg: "Mañana retiro a las 11:30 AM por cita médica con el pediatra.",
    sendBtn: "Enviar Reporte a Sala",
    successMsg: "¡Mensaje enviado a la Docente Karina! Se notificará su lectura en el receso."
  },
  sidebar: {
    achievementsTitle: "Logros Recientes",
    levelBadge: "Nivel Nido 2",
    badge1Title: "Pinza de Oro",
    badge1Desc: "Destreza motriz fina y autonomía",
    badge2Title: "Lector Estrella",
    badge2Desc: "Reconocimiento de 5 fonemas",
    badge3Title: "Amigo Colaborador",
    badge3Desc: "Ordenó y compartió material",
    viewAllBadges: "Ver todas las medallas (8) →",
    aiBadge: "💡 Sugerencia Semanal IA",
    aiTip: "“Tip para Mateo en casa: Para potenciar el 85% alcanzado en motricidad fina, refuercen juegos de encastre y amasado con plastilina durante 10 minutos antes de la cena.”",
    aiActionBtn: "Ver 3 Juegos para Casa 🏡",
    remindersTitle: "Próximos Recordatorios",
    rem1Title: "Reunión Trimestral de Familias",
    rem1Desc: "16:00 hrs • Sesión Virtual",
    rem2Title: "Día del Sombrero Loco & Huerta",
    rem2Desc: "Traer sombrero de reciclaje",
    syncCalendar: "Sincronizar con Google Calendar",
    teacherContactTitle: "Contacto de Sala",
    teacherRole: "Guía AMI Titular Aula Semillitas",
    teacherAvailability: "Disponible en receso (13:00 - 14:00)",
    whatsappBtn: "WhatsApp Institucional"
  },
  hero: {
    greeting: "¡Hola, Familia",
    summaryStart: "Este es el resumen de",
    summaryMiddle: "hoy en el",
    presentBadge: "PRESENTE HOY",
    ageBadge: "3 Años cumplidos",
    classroomBadge: "Aula Semillitas",
    attendanceBadge: "Asistencia: 08:15 AM (Biométrico)",
    teacherBadge: "Guía: Docente Karina S.",
    sendNoteBtn: "+ ENVIAR NOTA A LA DOCENTE",
    yearsOld: "Años cumplidos",
    guide: "Guía: "
  },
    nav: {
      myChild: "Mi Hijo/a",
      reports: "Mis Comentarios/Reportes",
      calendar: "Calendario de Actividades",
      games: "Mundo Juegos",
      backToDashboard: "Panel de Padres",
      backToDashboardShort: "Panel Padres",
      goToGames: "Ir a Juegos",
      aiAssistant: "AI Asistente",
      userRole: "Mamá de Mateo"
    },
    profileSettings: {
      title: "Configuración de Perfil",
      subtitle: "Actualiza tus datos y foto",
      photoLabel: "Foto de Perfil",
      quickOptions: "Opciones rápidas o iniciales:",
      initialsBtn: "Iniciales",
      uploadDeviceBtn: "Seleccionar foto del dispositivo",
      changePhotoHover: "Cambiar foto desde el dispositivo",
      urlPlaceholder: "O pega una URL de foto web (https://...)",
      nameLabel: "Nombre Completo",
      namePlaceholder: "Tu nombre completo...",
      emailLabel: "Correo Electrónico",
      emailPlaceholder: "ejemplo@correo.com",
      cancelBtn: "Cancelar",
      saveBtn: "Guardar Cambios",
      savingBtn: "Guardando...",
      successMessage: "¡Perfil actualizado con éxito!",
      localSuccessMessage: "¡Perfil guardado localmente!",
      errorNameRequired: "El nombre no puede estar vacío.",
      errorEmailRequired: "El correo electrónico no puede estar vacío.",
      errorInvalidImage: "Por favor selecciona un archivo de imagen válido (JPG, PNG, WEBP, etc.).",
      errorImageSize: "La imagen seleccionada no debe superar los 5MB.",
      settingsTooltip: "Configuración de perfil"
    },
  },
  reportsPage: {
      syncedWith: "Sincronizado con",
      pageTitle1: "Bandeja",
      pageTitle2: "de",
      pageTitle3: "Comunicación",
      pageTitle4: "y",
      pageTitle5: "Reportes",
      pageSubtitle: "Historial de notas enviadas y respuestas de",
      pageSubtitleMid: "•",
      composeBtn: "Redactar Nuevo Mensaje",
      filterAll: "Todos",
      filterHealth: "Consultas de Salud",
      filterSchedule: "Avisos de Retiro/Horario",
      filterPedagogical: "Observaciones Pedagógicas",
      composerTitle: "Redactar Nuevo Mensaje / Reporte",
      composerSubtitle: "Envía una notificación directa a la guía a cargo del aula.",
      categoryLabel: "Categoría del reporte",
      catHealth: "Consulta de Salud",
      catSchedule: "Aviso de Horario",
      catPedagogical: "Observación Pedagógica",
      catHealthFull: "Consulta de Salud",
      catScheduleFull: "Aviso de Horario / Retiro",
      catPedagogicalFull: "Observación Pedagógica",
      subjectLabel: "Asunto o Título",
      subjectPlaceholder: "Ej: Administración de medicamento matutino...",
      messageLabel: "Mensaje o Indicaciones",
      messagePlaceholder: "Escribe los detalles aquí...",
      attachBtn: "Adjuntar Receta o Documento",
      sendBtn: "Enviar Reporte",
      sentJustNow: "Enviado justo ahora",
      historyTitle: "Historial de Notas Recientes",
      sortRecent: "Más recientes primero",
      sortPending: "Pendientes de respuesta",
      sortCategory: "Por categoría",
      statusConfirmed: "Confirmado",
      statusPending: "Pendiente",
      emptyTitle: "No tienes reportes o notas registradas aún.",
      emptyDesc: "Usa el formulario de arriba para enviar tu primera consulta o reporte a la docente.",
      deleteTitle: "Eliminar nota antes de ser respondida",
      signedLabel: "Firmado digitalmente por Enfermería y Guía",
      sidebarContactTitle: "Contacto Directo de Sala",
      sidebarOnlineTitle: "En línea en el aula",
      sidebarBreakHours: "Receso familias: 13:00 - 14:00 hrs",
      sidebarExtension: "Anexo de Recepción / Sala:",
      sidebarAiBadge: "Asistente IA • Guía Familiar",
      sidebarAiTitle: "¿Cómo redactar un reporte de salud efectivo?",
      sidebarAiSubtitle: "Para garantizar la seguridad farmacológica de tu hijo/a en el aula nido:",
      sidebarStep1: "Especificar",
      sidebarStep1Bold: "dosis exacta",
      sidebarStep1End: "(ml/gotas) y horario fijado.",
      sidebarStep2: "Indicar si requiere",
      sidebarStep2Bold: "refrigeración previa",
      sidebarStep2End: "en recepción.",
      sidebarStep3: "Adjuntar siempre la",
      sidebarStep3Bold: "receta o autorización",
      sidebarStep3End: "firmada.",
      sidebarTemplateBtn: "Usar Plantilla Rápida de Salud",
      sidebarNormTitle: "Horarios de Retiro y Normativa",
      sidebarNormDesc: "Todo adulto autorizado distinto de los tutores titulares debe portar documento de identidad y estar previamente registrado en el portal.",
      sidebarEntryLabel: "Entrada habitual:",
      sidebarExitLabel: "Salida ordinaria:",
    },
    calendarPage: {
      activitiesPanel: "Panel de Actividades",
      titleWord1: "Calendario",
      titleWord2: "y",
      titleWord3: "Actividades",
      syncBtn: "Sincronizar con Google Calendar / iCal",
      prevMonth: "Mes Anterior",
      nextMonth: "Mes Siguiente",
      viewMonth: "Mes",
      viewWeek: "Semana",
      viewAgenda: "Agenda",
      filterAll: "Todos los eventos",
      filterSpecial: "Actividades Especiales (2)",
      filterMeetings: "Reuniones de Padres (1)",
      filterWorkshops: "Talleres Estimulación (2)",
      months: [
        "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
        "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
      ],
      daysOfWeek: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
      toastSync: "Sincronizando eventos con tu calendario iCal/Google...",
      toastFilter: "Filtrando actividades",
      toastViewChanged: "Vista cambiada a modo: ",
      toastReminderScheduled: "Recordatorio agendado",
      toastRsvpUnchecked: "Asistencia desmarcada temporalmente",
      toastRsvpChecked: "¡Asistencia confirmada para {name}!",
      toastDownloadingGuide: "Descargando Guía Pedagógica Sombrero Loco (PDF 1.4MB)",
      toastAllMaterialsReady: "¡Todos los materiales de la semana listos!",
      eventsThisMonth: "Eventos este mes",
      upcomingActivities: "Próximas Actividades",
      chronologicalOrder: "Orden cronológico",
      noEvents: "No hay eventos para este filtro o mes seleccionado.",
      events: {
        evt1Title: "Taller Fonemático y Estimulación",
        evt1Cat: "Estimulación AMI",
        evt1Desc: "Sesión práctica de desarrollo de lenguaje y habilidades fonológicas.",
        evt2Title: "Circuito Sensorial de Primavera",
        evt2Cat: "Lúdico / Huerta",
        evt2Desc: "Actividades al aire libre para exploración táctil y motricidad gruesa.",
        evt3Title: "Taller Fonemático Avanzado",
        evt3Cat: "Estimulación AMI",
        evt3Desc: "Continuación del taller de fonemas enfocado en articulación y vocabulario.",
        evt4Title: "Reunión Trimestral de Familias",
        evt4Cat: "Reunión Familias",
        evt4Desc: "Presentación de informes de avance académico y emocional del periodo.",
        evt5Title: "Día del Sombrero Loco",
        evt5Cat: "Lúdico / Huerta",
        evt5Desc: "Celebración temática interactiva. Recuerda traer el material reciclado.",
        evt5Time: "Durante la jornada"
      },
      upcomingSectionTitle: "Próximos Eventos y Actividades Destacadas",
      twoUpcomingBadge: "2 Próximos",
      oneUpcomingBadge: "1 Próximo",
      enrolledSubtitle: "matriculado/a en ambas",
      tuesday: "Martes",
      friday: "Viernes",
      october2026: "Octubre 2026",
      presentialBadge: "Presencial",
      virtualBadge: "Virtual vía Google Meet",
      tagGarden: "Huerta Pedagógica & Estimulación",
      tagNeuro: "Evaluación de Neurodesarrollo",
      locGarden: "Aula Semillitas & Patio Huerta Montessori",
      locNeuro: "Docente {teacher} + Psicopedagogía Montekids",
      event1Title: "Día del Sombrero Loco & Huerta Comunitaria",
      event1Desc: "Traer un sombrero decorado con elementos reciclados hechos en casa para la dinámica de estimulación sensorial, motricidad táctil y siembra de plantines en el huerto pedagógico junto a {name}.",
      event2Title: "Reunión Trimestral de Familias • Informe Bimestral",
      event2Desc: "Revisión conjunta personalizada del progreso motor fino, lenguaje activo y autorregulación de {name} según la rúbrica AMI. Se presentará el portafolio fotográfico bimestral.",
      rsvpConfirmed: "✓ Asistencia Confirmada",
      rsvpConfirm: "Confirmar Asistencia",
      downloadGuideBtn: "Descargar Guía de Actividad (PDF)",
      joinMeetBtn: "Unirse a Sesión Virtual (Google Meet)",
      viewAgendaBtn: "Ver Orden del Día",
      pedagogicalSummaryBadge: "Resumen Pedagógico de Octubre",
      pedagogicalSummaryTitle: "18 Sesiones Sensoriales Completadas",
      pedagogicalSummaryDesc: "{name} asistió al 96% de las actividades guiadas en su aula.",
      vsSept: "frente a Sept",
      materialsTitle: "Materiales Pendientes",
      materialsSubtitle: "Elementos necesarios para el {classroom} y actividades sensoriales de la semana:",
      ofCount: "de",
      item1Text: "Muda de ropa adicional para estimulación con agua y tierra",
      item1Sub: "Entregado en casillero #14",
      item2Text: "Materiales reciclados para el Sombrero Loco",
      item2Sub: "Pendiente para el Mar 31 Oct",
      item3Text: "1 fruta picada para la merienda compartida",
      item3Sub: "Uvas sin semillas asignadas",
      item4Text: "Botella de agua identificada con nombre térmico",
      item4Sub: "Revisar antes del lunes",
      aiAssistantBadge: "Asistente",
      aiTipBadge: "Tip Educativo",
      aiCardTitle: "¿Cómo armar el Sombrero en 15 min?",
      aiCardDesc: "Utiliza un plato de cartón o caja de cereales. Fomenta que tu hijo/a rasgue papel crepé y pegue tapitas: esta actividad estimula el reflejo de pinza trípode y su autonomía.",
      aiCardBtn: "Ver Paso a Paso",
      scheduleTitle: "Horario Habitual",
      scheduleRoutine: "Rutina Diaria",
      scheduleEntry: "Entrada habitual",
      scheduleEntryHours: "06:00 - 06:30 AM",
      scheduleSnack: "Merienda Sensorial",
      scheduleSnackHours: "10:00 - 10:30 AM",
      scheduleExit: "Salida ordinaria",
      scheduleExitHours: "5:00 - 5:30 PM",
      delayQuestion: "¿Retraso imprevisto en la recogida?",
      guidePrefix: "Guía",
      sendNoteBtn: "Enviar Comentario al Docente",
      onlineTooltip: "En línea",
      orderTitle: "Orden del Día",
      orderSubtitle: "Reunión Trimestral • 27 Octubre",
      orderStep1Title: "16:00 - 16:15 hrs: Bienvenida y Enfoque Bimestral",
      orderStep1Desc: "Introducción al método de observación Montessori del Aula Semillitas.",
      orderStep2Title: "16:15 - 16:40 hrs: Presentación Individual de Informes",
      orderStep2Desc: "Revisión del neurodesarrollo motor, esquema corporal e interacción de {name}.",
      orderStep3Title: "16:40 - 17:00 hrs: Espacio de Consultas con Psicopedagogía",
      orderStep3Desc: "Pautas para el acompañamiento en casa y estimulación del sueño autónomo.",
      orderUnderstoodBtn: "Entendido",
      aiModalTitle: "Guía Exprés: Sombrero de Huerta",
      aiModalSubtitle: "Asistente",
      aiModalObjTitle: "Objetivo Montessori:",
      aiModalObjDesc: "Dejar que tu hijo/a tome decisiones sobre colores y texturas, evitando corregir la simetría para reforzar su autonomía.",
      aiModalStep1Title: "Minuto 1 al 5: Base Estructurada",
      aiModalStep1Desc: "Recortar la base utilizando un cono de cartón o plato biodegradable reciclado.",
      aiModalStep2Title: "Minuto 5 al 10: Pintura Sensorial",
      aiModalStep2Desc: "Dejar que {name} pinte libremente con sus deditos tonos verdes y naranjas simulando zanahorias y hojas.",
      aiModalStep3Title: "Minuto 10 al 15: Textura Táctil",
      aiModalStep3Desc: "Adherir ramitas secas y hojas caídas del parque utilizando pegamento al agua no tóxico.",
      aiModalReadyBtn: "¡Listo para crear!"
    },
    adminDashboard: {
      assignedClassroom: "Tu Aula Asignada",
      exportReport: "Exportar Informe",
      newEvaluation: "+ Nueva Evaluación",
      activeCensus: "Censo Activo",
      registeredChildren: "Niños Registrados",
      students: "Alumnos",
      roomCapacity: "Capacidad de sala: 96%",
      freeSpot: "1 cupo libre",
      starsEconomy: "Economía de Estrellas",
      accumulatedStars: "Estrellas Acumuladas",
      totalStars: "Estrellas Totales",
      noStarsYet: "Sin estrellas aún",
      gamesActivity: "Actividad de Juegos",
      sessionsCompleted: "Sesiones Realizadas",
      totalGames: "Juegos Totales",
      noGamesYet: "Aún no hay juegos",
      longitudinalPanel: "Panel Longitudinal",
      metricsTitle: "Métricas de Desarrollo y Progresión",
      last6Months: "Últimos 6 Meses",
      quarter: "Trimestre",
      annual: "Anual",
      psychomotorSensory: "Psicomotriz y Sensorial",
      cognitiveLanguage: "Cognitivo y Lenguaje",
      socioemotional: "Socioemocional",
      attendanceRecord: "Registro de Asistencia",
      takeAttendance: "PASAR LISTA Y REVISAR HISTORIAL",
      prevDay: "◄ Anterior",
      today: "Hoy",
      nextDay: "Siguiente ►",
      showCalendar: "🗓️ Ver Calendario",
      hideCalendar: "🗓️ Ocultar Calendario",
      prevMonth: "‹ Mes Ant.",
      nextMonth: "Mes Sig. ›",
      tutor: "Tutor:",
      present: "Presente",
      absent: "Ausente",
      noStudentsInClass: "No hay estudiantes registrados en esta aula.",
      attendanceSummary: "Resumen Asistencia",
      presentCountLabel: "presentes",
      absentCountLabel: "ausentes",
      montessoriTipTitle: "TIP MONTESSORI DEL DÍA",
      montessoriTipText: '"Cualquier ayuda innecesaria es un obstáculo para el desarrollo infantil." Permite 3 intentos autónomos antes de asistir en la abotonadura.',
      teachingSection: "SECCIÓN DE DOCENCIA",
      studentsManagementTitle: "Gestión y Registro de Alumnos",
      studentsManagementSubtitle: "Revisa información de cada niño/a, envía comentarios a su bitácora y asigna actividades o materiales.",
      searchStudentPlaceholder: "Buscar alumno o tutor...",
      noStudentsFound: "No se encontraron estudiantes para los criterios seleccionados.",
      tutorLabel: "Tutor:",
      genderLabel: "GÉNERO",
      girl: "👧 Niña",
      boy: "👦 Niño",
      ageLabel: "EDAD",
      assignedClassroomLabel: "AULA ASIGNADA",
      unassignedClassroom: "Sin aula asignada",
      sendNoteBtn: "💬 Enviar Comentario a Bitácora",
      assignTaskBtn: "📋 Asignar Actividad o Material",
      planningHeader: "PLANIFICACIÓN EDUCATIVA Y CALENDARIO",
      curriculumTitle: "Plan Curricular de",
      allClassrooms: "Todas las Aulas",
      curriculumSubtitle: "Programa temas y actividades para cada fecha. Se sincronizan automáticamente con el calendario de las familias.",
      searchCurriculumPlaceholder: "Buscar en el plan curricular...",
      addCurriculumBtn: "+ Programar Actividad",
      noCurriculumEvents: "No hay actividades programadas en el plan curricular. Haz clic en \"+ Programar Actividad\" para añadir una nueva.",
      deleteEventTitle: "Eliminar del plan curricular",
      deleteBtn: "Eliminar",
      reportsHeader: "ATENCIÓN Y MENSAJERÍA A FAMILIAS",
      reportsTitle: "Reportes y Comentarios del",
      reportsSubtitle: "Revisa los avisos de salud, permisos u observaciones enviadas por los tutores y responde directamente a sus mensajes.",
      totalMessages: "Mensajes en Total",
      filterByTutor: "👨‍👩‍👧‍👦 Filtrar por Tutor de Estudiante:",
      allTutors: "🌐 Todos los Tutores",
      noReportsForTutor: "No hay reportes o mensajes registrados para el tutor seleccionado.",
      pendingResponse: "Pendiente de respuesta por la docente",
      replyToTutor: "Responder al Tutor",
      modifyReply: "Modificar Respuesta",
      noteModalTitle: "💬 Enviar Comentario a Bitácora",
      targetStudentLabel: "Estudiante destinatario:",
      writeNoteLabel: "Escribe tu observación o comentario pedagógico:",
      notePlaceholder: "Ej: Exploró con entusiasmo el material sensorial y participó activamente en la rutina...",
      sendToLogBtn: "Enviar a Bitácora",
      cancelBtn: "Cancelar",
      taskModalTitle: "📋 Asignar Actividad o Material",
      assignToLabel: "Asignar a:",
      taskTitleLabel: "Título del Material o Tarea:",
      taskTitlePlaceholder: "Ej: Materiales reciclados para el Sombrero Loco...",
      taskSubtitleLabel: "Nota / Indicación adicional:",
      taskSubtitlePlaceholder: "Ej: Pendiente para el Mar 31 Oct",
      taskIconLabel: "Icono representativo:",
      assignToCalendarBtn: "Asignar a Calendario",
      currModalTitle: "📅 Programar Actividad Curricular",
      currTitleLabel: "Título de la Actividad o Tema:",
      currTitlePlaceholder: "Ej: Taller de Expresión Plástica y Texturas...",
      currDateLabel: "Fecha:",
      currTimeLabel: "Horario:",
      currTimePlaceholder: "Ej: 09:00 AM - 10:30 AM",
      currCategoryLabel: "Área / Categoría:",
      catWorkshops: "Estimulación AMI (Talleres)",
      catSpecial: "Lúdico / Huerta / Actividades Especiales",
      catMeetings: "Reunión Familias / Institucional",
      catAcademic: "Área Académica / Expresión",
      currDescLabel: "Descripción Pedagógica u Observaciones:",
      currDescPlaceholder: "Detalla los objetivos pedagógicos o lo que los estudiantes realizarán ese día...",
      saveToCalendarBtn: "Guardar en Calendario",
      replyModalTitle: "💬 Responder a",
      tutorInquiryLabel: "Consulta del Familiar:",
      replyStatusLabel: "Etiqueta de Estado de Respuesta:",
      optAttended: "✓ Atendido / Enterado",
      optDose: "💊 Dosis o Medicamento Administrado",
      optPermission: "⏰ Horario / Permiso Autorizado",
      optObs: "📝 Registrado en Ficha",
      replyMessageLabel: "Respuesta o Mensaje para el Tutor:",
      replyPlaceholder: "Escribe la respuesta que se mostrará en el panel del familiar...",
      sendReplyBtn: "Enviar Respuesta",
      nav: {
        dashboard: "Dashboard",
        students: "Alumnos",
        curriculum: "Plan Curricular",
        evaluations: "Evaluaciones",
        reports: "Reportes"
      }
    }
  },
  en: {
    nav: {
      home: 'Home',
      philosophy: 'Philosophy',
      classrooms: 'Classrooms',
      reviews: 'Reviews',
      contact: 'Location & Contact',
      aiAssistant: 'AI Assistant',
      login: 'Log In',
      backToHome: 'Back to Home',
      changeTextSize: 'Change text size',
      changeTheme: 'Toggle theme',
      colorblind: 'Color filter',
      language: 'Language'
    },
    cancionesPage: {
      badgeSection: 'RHYTHMIC CORNER',
      badgeCategory: 'Educational Music Videos',
      title: 'Animated Children\'s Songs',
      playingBadge: 'PLAYING VIDEO',
      starsReward: '+5 Stars for singing complete',
      playVideo: 'Play Video',
      pauseVideo: 'Pause Video',
      restartVideo: 'Restart',
      speedLabel: 'SPEED:',
      speedSlow: '0.8x Slow',
      speedNormal: '1.0x Normal',
      speedFast: '1.2x Fast',
      catalogTitle: 'Choose Your Favorite Song!',
      seeAll: 'See all',
      dailyMissionTitle: 'DAILY MISSION • ATTENTIVE LISTENER',
      dailyMissionLevel: 'Explorer Level',
      dailyMissionBannerTitle: 'Sing and listen to songs to earn more golden stars!',
      dailyMissionBannerDesc: 'Each played song helps the explorer associate sounds while having fun with Lottie Dottie Chicken videos.',
      goalOfDay: 'Goal of the Day',
      remainingSongs: 'songs remaining!',
      bonusReward: '+10 ★ Bonus'
    },
    hero: {
      badge: 'Early Stimulation Center',
      titleStart: 'The Place Where',
      wordLearn: 'Learning',
      and: 'and',
      wordGrow: 'Growing',
      isAn: 'is a',
      wordAdventure: 'Magical',
      wordMagical: 'Adventure',
      desc: 'Early stimulation, psychomotor development and active learning for babies and children in a safe, affectionate environment guided by natural curiosity.',
      btnWhatsapp: 'Start Chat on WhatsApp',
      btnLocation: 'View Location',
      sensoryTitle: 'Active Sensory Session',
      sensoryDesc: 'Fine Motor Skills & Coordination',
      live: 'Live'
    },
    philosophy: {
      badge: 'AMI Philosophy & Methodology',
      title: 'Our Educational Philosophy and Methodology',
      desc: 'Three pillars designed to respect sensitive periods, innate curiosity, and comprehensive neurodevelopment.',
      c1Badge: '360° Development',
      c1Title: 'Comprehensive Early Stimulation 🧠',
      c1Desc: 'Integration of cognitive, motor, sensory, and socio-linguistic milestones through exploration with hands-on Montessori materials.',
      c1Footer: 'Sensory-Motor Circuits',
      c2Badge: 'Continuous Connection',
      c2Title: 'Family Support & Guidance 📱',
      c2Desc: 'Exclusive guardian access: real-time daily log, photo record of achievements, and direct teacher communication.',
      c2Footer: 'Montekids Family App',
      c3Badge: 'Pedagogical Innovation',
      c3Title: 'Continuous Tracking with AI 🌟',
      c3Desc: 'Synergy between expert educators and adaptive analytics to suggest personalized dynamics at each child’s pace.',
      c3Footer: 'Personalized Plans'
    },
    programs: {
      badge: 'Educational Programs',
      title: 'Our Classrooms and Developmental Levels',
      desc: 'Carefully prepared environments with child-scaled ergonomic furniture and self-correcting materials.',
      cycle: 'School Year 2027',
      openEnrollment: 'Enrollment Open',
      consultBtn: 'Check Availability',
      r1Age: '2 to 3 Years',
      r1Title: 'Little Seeds Room',
      r1Desc: 'Deep sensory stimulation, foundational communication structures, exploratory gross motor skills, and secure attachment.',
      r1Ratio: '1 Educator per 5 children',
      r1Cap: '10 children max per room',
      r1Sched: 'Morning (8:30 to 12:30)',
      r1Assigned: '80% Spots Filled',
      r1Free: '2 Spots Available',
      r2Age: '3 to 4 Years',
      r2Title: 'Explorers Room',
      r2Desc: 'Active language development, cooperative socialization, pre-logical thinking, and daily independence.',
      r2Ratio: '1 Educator per 7 children',
      r2Cap: '14 children max per room',
      r2Sched: 'Full or Half Day',
      r2Assigned: '65% Spots Filled',
      r2Free: '5 Spots Available',
      r3Age: '4 to 5 Years',
      r3Title: 'Creators Room',
      r3Desc: 'Sensory phonetic pre-literacy, refined fine motor skills, scientific projects, and playful discovery challenges.',
      r3Ratio: '1 Educator per 8 children',
      r3Cap: '16 children max per room',
      r3Sched: 'Full Day (8:30 to 16:30)',
      r3Assigned: '88% Spots Filled',
      r3Free: 'Last Spots',
      ratioLabel: 'Ratio:',
      capLabel: 'Capacity:',
      schedLabel: 'Schedule:'
    },
    IMAS: {
      badge: 'IMAS Benefit',
      title: 'Does your child receive an IMAS benefit?',
      desc: 'If your child currently attends another daycare, you can request a transfer to MONTEKIDS. Our team will guide you through the entire process.',
      cycle: 'School Year 2027',
      openEnrollment: 'Enrollment Open',
      consultBtn: 'Check Availability',
      r1Age: 'Step 1',
      r1Title: 'Complete the IMAS online service form with your personal details, ID number, and your child’s information.',
      r1Desc: '',
      r1Ratio: '',
      r1Cap: '',
      r1Sched: '',
      r1Assigned: '',
      r1Free: '2 Spots Available',
      r2Age: 'Step 2',
      r2Title: 'Specify in the details or notes section that you are requesting a transfer of Child Care and Development Center (CECUDI) or Red de Cuido, stating the reason for the transfer and your preferred center.',
      r2Desc: '',
      r2Ratio: '',
      r2Cap: '',
      r2Sched: '',
      r2Assigned: '65% Spots Filled',
      r2Free: '5 Spots Available',
      r3Age: 'Step 3',
      r3Title: 'Submit the application and wait for a social worker to contact you to validate the transfer and verify available space at the new location.',
      r3Desc: '',
      r3Ratio: '',
      r3Cap: '',
      r3Sched: '',
      r3Assigned: '',
      r3Free: 'Last Spots',
      ratioLabel: 'Ratio:',
      capLabel: 'Capacity:',
      schedLabel: 'Schedule:'
    },
    testimonials: {
      badge: 'Community & Trust',
      title: 'Happy Families at Montekids',
      desc: 'Real testimonials from families who trust in our educational accompaniment.',
      t1Text: '“Outstanding care and methodology. Mateo has made huge strides in language, autonomy, and motor skills. Plus the web app keeps us informed about every daily milestone.”',
      t1Author: 'Valeria Quirós',
      t1Role: 'Mateo’s Mom (Explorers Room)',
      t2Text: '“The environment is affectionate and inspiring. The teachers are highly skilled, and the individual-paced approach makes a world of difference in Sofi’s self-confidence.”',
      t2Author: 'Carlos Mendoza',
      t2Role: 'Sofía’s Dad (Creators Room)',
      c1Val: '+150',
      c1Title: 'Happy Children',
      c1Desc: 'Actively guided',
      c2Val: '12',
      c2Title: 'Years of Experience',
      c2Desc: 'Cutting-edge education',
      c3Val: '100%',
      c3Title: 'Connected Families',
      c3Desc: 'In-app daily monitoring',
      c4Val: '5/5 ★',
      c4Title: 'Average Rating',
      c4Desc: 'Verified satisfaction'
    },
    location: {
      badge: 'Location & Direct Contact',
      title: 'Visit Us and Get in Touch',
      desc: 'Would you like to tour our facilities or inquire about admissions? Reach out directly or come visit us.',
      hoursBadge: 'Open 6:00 AM - 6:00 PM',
      hqTitle: 'Montekids Central Campus',
      address: '5A Ave, Puntarenas Province, El Roble, El Roble 2, 60101',
      scheduleLabel: 'Hours:',
      scheduleVal: 'Mon - Fri: 6:00 AM - 6:00 PM',
      phoneLabel: 'Phone:',
      emailLabel: 'Email:',
      btnWhatsapp: 'Start Chat on WhatsApp'
    },
    cta: {
      badge: 'Admissions 2027',
      title: 'Ready to empower your little one’s future?',
      desc: 'Limited spots for the 2027 school year. Schedule your in-person or virtual guided tour today and discover how we make every breakthrough memorable.',
      btnChat: 'Start Chat on WhatsApp',
      f1: 'Immediate response',
      f2: 'Personalized 40-min tour'
    },
    footer: {
      desc: 'Montessori Comprehensive Early Development & Stimulation Center. Cultivating wonder and natural autonomy from the very first steps.',
      certAmi: 'International AMI Certification',
      explore: 'Explore',
      linkPhil: 'Our philosophy',
      linkClass: 'Classrooms',
      linkRev: 'Reviews',
      linkLoc: 'Location & contact',
      contact: 'Contact',
      locPuntarenas: 'El Roble, Puntarenas',
      hours: 'Hours: Mon to Fri 06:00 - 18:00 hrs',
      copy: '© 2026 Montekids Early Childhood & Stimulation Center. All rights reserved.',
      privacy: 'Privacy Policy',
      protocol: 'Child Welfare Protocol'
    },
    auth: {
      tabLogin: 'Log In',
      tabRegister: 'Register',
      certBar: 'AMI Certified Platform • School-Grade Biometric Encryption',
      communityBar: 'Montekids Community • +1,400 Connected Families',
      montessoriBadge: 'Montessori Digital AMI',
      heroTitle: 'Guiding Your Child’s Growth 🌟',
      heroDesc: 'Access daily activity reports, sensory stimulation photo logs, classroom nursery rhymes, and direct messaging with guide educators.',
      heroF1: 'Real-time monitoring & live logs',
      heroF2: 'Motor & phonetic milestones tracking',
      heroF3: 'Secure portal for badges & achievements',
      trust1Title: 'Ironclad Privacy',
      trust1Desc: 'Strict COPPA & GDPR-K compliance',
      trust2Title: 'AMI Association',
      trust2Desc: 'Verified Montessori methodology',
      trust3Title: 'Family Support',
      trust3Desc: '24/7 pedagogical help desk',
      schoolCycle: 'School Year 2025 • Spring Term',
      loginWord1: 'Welcome',
      loginWord2: 'Back!',
      loginWord3: '',
      loginSubtitle: 'Log in to your account to continue real-time tracking of your little explorer and review their sensory logs.',
      googleAuth: 'Continue with Google Workspace for Education',
      orDivider: 'or with your credentials',
      emailLabel: 'Registered Email Address',
      emailPlaceholder: 'e.g. mateo.mom@email.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      forgotPassword: 'Forgot your password?',
      rememberMe: 'Remember on this device for 30 days',
      submitLogin: 'Enter Virtual Classroom',
      noAccountText: 'Don’t have a registered account for your child yet?',
      registerLink: 'Register Here ✨',
      regSchoolCycle: 'Family Enrollment • 2025 Cycle',
      regWord1: 'Create',
      regWord2: 'Your',
      regWord3: 'Family',
      regWord4: 'Account',
      regWord5: '',
      regSubtitle: 'Securely link direct access to the classroom and your child’s personalized log at Montekids.',
      regNameLabel: 'Guardian or Parent Full Name',
      regNamePlaceholder: 'e.g. Valeria Quirós Fernández',
      regEmailLabel: 'Contact Email Address',
      regEmailPlaceholder: 'your.email@example.com',
      regCodeLabel: 'Classroom / Student Code',
      regCodeBadge: 'Provided at Front Desk',
      regCodePlaceholder: 'e.g. MK-2025-EXPLO-88',
      createPassLabel: 'Create Secure Password',
      createPassPlaceholder: 'Minimum 8 characters',
      termsText1: 'I accept the',
      termsLink: 'Terms of Service',
      termsText2: 'and authorize processing under',
      privacyLink: 'AMI Policy',
      submitRegister: 'Create Family Account ✨',
      haveAccountText: 'Already have an active guardian account?',
      loginLink: 'Log In Here 🔒',
      passNone: 'No password',
      passWeak: 'Weak',
      passGood: 'Good',
      passStrong: 'Strong & Secure',
      invalidCredentials: "Invalid email or password. Please check your credentials.",
      connectionError: "Could not connect to authentication server.",
      loggingIn: "Logging in...",
      loginButton: "Log In",
    },
    ai: {
      title: 'AI Virtual Assistant 🤖',
      online: 'Online and ready to help',
      welcome: "Hi! I\u2019m Montekids\u2019 AI assistant. How can I help you today? (e.g. schedules, location, or contact via WhatsApp)",
      reply: 'Great question! Our teaching team and available spots are ready. Would you like to set up a direct WhatsApp call?',
      placeholder: 'Type your question here...'
    },
    forgotPassword: {
      backToLogin: "Back to Login",
      title1: "Forgot",
      title2: "your",
      title3: "Password?",
      desc: "Enter the email address associated with your family or guardian account, and we will send you recovery instructions immediately.",
      emailLabel: "Registered Email Address",
      emailPlaceholder: "e.g. mateo.mom@email.com",
      expirationNotice: "The verification link will expire in 15 minutes due to strict school safety and child protection under COPPA protocol.",
      submitBtn: "Send Recovery Link",
      viewMode: "View:",
      formView: "Form",
      sentView: "Sent",
      errorCode: "The verification code is incorrect.",
      panelBadge: "Montessori Digital AMI",
      panelTitle: "Protecting Access to Your Child's Information 🛡️",
      panelDesc: "At Montekids, we safeguard your child's sensory logs, photos, and developmental assessments under the highest pedagogical standards.",
      card1Title: "Two-step verification active",
      card1Desc: "Immediate notification to primary guardian upon any access credential changes.",
      card2Title: "Direct support with office",
      card2Desc: "If you lost access to your email, our team verifies your identity securely in person.",
      card3Title: "Single-use encrypted token",
      card3Desc: "Ensures password recovery is only processed by the registered account owner.",
      noAccess: "No longer have access to this mailbox?",
      contactSchool: "Contact School Office",
      encryptionLabel: "Encryption",
      sessionIdLabel: "Session ID",
      successTitle: "Recovery email sent!",
      successInstructions: "We have sent the instructions to",
      resendAvailableIn: "Resend email available in",
      resendNow: "Resend verification email!",
      verifyAnotherEmail: "Verify another address",
      goToLogin: "Go to Login",
      validateAndLogin: "Validate and Log In",
      attemptsUsed: "Attempts used",
      incompleteCodeError: "Please enter all 6 digits of the verification code.",
    },
    parentDashboard: {
      header: {
        badge: "Comprehensive Monitoring Dashboard",
        title1: "Daily",
        title2: "Log",
        title3: "& Family",
        title4: "Progress",
        subtitle: "Real-time supervision of sensory, cognitive development and activities for",
        reportsBtn: "My Reports & Notes"
      },
      metrics: {
    fineMotor: "Fine Motor Skills",
    physicalArea: "Physical Area",
    fineMotorBadge: "🌟 Excellent pincer grasp!",
    fineMotorDesc: "Achieved independent fitting and seed transfer with an ergonomic spoon without difficulty.",
    language: "Language & Expression",
    communicationArea: "Communication",
    languageBadge: "💬 Knows 6 new words",
    languageDesc: "Fluent pronunciation of /M/ and /P/ phonemes and formulation of continuous 4-element phrases.",
    sensory: "Sensory & Cognitive",
    cognitionArea: "Cognition",
    sensoryBadge: "🧩 Progressing in patterns",
    sensoryDesc: "Recognizes color sequences and enjoys the natural texture box with great attention."
  },
  timeline: {
    headerTitle: "Daily Log",
    today: "Today, October 28, 2026",
    inSession: "In Morning Session",
    completedSuccess: "Successfully Completed",
    completedAt: "Completed at 11:15 AM",
    inProgress: "Currently in progress",
    teacherName: "Teacher Karina S.",
    act1Title: "Phonemes & Songs Workshop",
    act1Area: "Language Area",
    act1Time: "09:15 AM - 10:00 AM",
    act1Note: "“Mateo happily participated in identifying the letter M in the rhyme wagon. Showed great enthusiasm singing with Sofía and Lucas.”",
    act2Title: "Texture Circuit & Olfactory Stimulation",
    act2Area: "Sensory Area",
    act2Time: "10:30 AM - 11:15 AM",
    act2Note: "“Explored trays with lavender and seeds without tactile resistance. His tolerance and composure were excellent.”",
    act3Title: "Collaborative Garden & Healthy Snack",
    act3Desc: "Schedule: 11:45 AM - 12:30 PM • Guided cherry tomato harvest and handwashing.",
    formTitle: "Send a report or query to daycare",
    formDesc: "Communicate directly with Teacher Karina or the front desk team.",
    cat1: "Health Query",
    cat2: "Schedule / Pickup Notice",
    cat3: "Pedagogical Query",
    placeholder: "E.g. Tomorrow pickup at 11:30 AM due to a pediatrician appointment...",
    defaultMsg: "Tomorrow pickup at 11:30 AM due to a pediatrician appointment.",
    sendBtn: "Send Report to Classroom",
    successMsg: "Message sent to Teacher Karina! Read receipt notification will be sent during break."
  },
  sidebar: {
    achievementsTitle: "Recent Achievements",
    levelBadge: "Nest Level 2",
    badge1Title: "Golden Pincer",
    badge1Desc: "Fine motor skill & autonomy",
    badge2Title: "Star Reader",
    badge2Desc: "Recognition of 5 phonemes",
    badge3Title: "Collaborative Friend",
    badge3Desc: "Organized and shared materials",
    viewAllBadges: "View all badges (8) →",
    aiBadge: "💡 Weekly AI Suggestion",
    aiTip: "“Tip for Mateo at home: To boost the 85% achieved in fine motor skills, reinforce fitting games and playdough kneading for 10 minutes before dinner.”",
    aiActionBtn: "View 3 Home Games 🏡",
    remindersTitle: "Upcoming Reminders",
    rem1Title: "Quarterly Family Meeting",
    rem1Desc: "04:00 PM • Virtual Session",
    rem2Title: "Crazy Hat & Garden Day",
    rem2Desc: "Bring recycled hat",
    syncCalendar: "Sync with Google Calendar",
    teacherContactTitle: "Classroom Contact",
    teacherRole: "Lead AMI Guide - Little Seeds Room",
    teacherAvailability: "Available during break (13:00 - 14:00)",
    whatsappBtn: "Institutional WhatsApp"
  },
  hero: {
    greeting: "Hello, Family",
    summaryStart: "Here is the daily summary for",
    summaryMiddle: "today at",
    presentBadge: "PRESENT TODAY",
    ageBadge: "3 Years old",
    classroomBadge: "Little Seeds Room",
    attendanceBadge: "Attendance: 08:15 AM (Biometric)",
    teacherBadge: "Guide: Teacher Karina S.",
    sendNoteBtn: "+ SEND NOTE TO TEACHER",
    yearsOld: "Years old",
    guide: "Guide: "
  },
    nav: {
      myChild: "My Child",
      reports: "My Comments/Reports",
      calendar: "Activities Calendar",
      games: "Games World",
      backToDashboard: "Parents Dashboard",
      backToDashboardShort: "Parents Panel",
      goToGames: "Go to Games",
      aiAssistant: "AI Assistant",
      userRole: "Mateo's Mom"
    },
    profileSettings: {
      title: "Profile Settings",
      subtitle: "Update your details and photo",
      photoLabel: "Profile Photo",
      quickOptions: "Quick options or initials:",
      initialsBtn: "Initials",
      uploadDeviceBtn: "Select photo from device",
      changePhotoHover: "Change photo from device",
      urlPlaceholder: "Or paste a web photo URL (https://...)",
      nameLabel: "Full Name",
      namePlaceholder: "Your full name...",
      emailLabel: "Email Address",
      emailPlaceholder: "example@email.com",
      cancelBtn: "Cancel",
      saveBtn: "Save Changes",
      savingBtn: "Saving...",
      successMessage: "Profile updated successfully!",
      localSuccessMessage: "Profile saved locally!",
      errorNameRequired: "Name cannot be empty.",
      errorEmailRequired: "Email cannot be empty.",
      errorInvalidImage: "Please select a valid image file (JPG, PNG, WEBP, etc.).",
      errorImageSize: "Selected image must not exceed 5MB.",
      settingsTooltip: "Profile settings"
    },
  },
  reportsPage: {
      syncedWith: "Synced with",
      pageTitle1: "Communication",
      pageTitle2: "&",
      pageTitle3: "Reports",
      pageTitle4: "Inbox",
      pageTitle5: "",
      pageSubtitle: "History of notes sent and replies from",
      pageSubtitleMid: "•",
      composeBtn: "Compose New Message",
      filterAll: "All",
      filterHealth: "Health Queries",
      filterSchedule: "Schedule / Pickup Notices",
      filterPedagogical: "Pedagogical Observations",
      composerTitle: "Compose New Message / Report",
      composerSubtitle: "Send a direct notification to the classroom guide.",
      categoryLabel: "Report category",
      catHealth: "Health Query",
      catSchedule: "Schedule Notice",
      catPedagogical: "Pedagogical Observation",
      catHealthFull: "Health Query",
      catScheduleFull: "Schedule / Pickup Notice",
      catPedagogicalFull: "Pedagogical Observation",
      subjectLabel: "Subject or Title",
      subjectPlaceholder: "E.g.: Morning medication administration...",
      messageLabel: "Message or Instructions",
      messagePlaceholder: "Write the details here...",
      attachBtn: "Attach Prescription or Document",
      sendBtn: "Send Report",
      sentJustNow: "Sent just now",
      historyTitle: "Recent Notes History",
      sortRecent: "Most recent first",
      sortPending: "Pending reply",
      sortCategory: "By category",
      statusConfirmed: "Confirmed",
      statusPending: "Pending",
      emptyTitle: "You have no reports or notes yet.",
      emptyDesc: "Use the form above to send your first query or report to the teacher.",
      deleteTitle: "Delete note before it is answered",
      signedLabel: "Digitally signed by Nursing & Guide",
      sidebarContactTitle: "Direct Classroom Contact",
      sidebarOnlineTitle: "Online in the classroom",
      sidebarBreakHours: "Family break: 1:00 PM - 2:00 PM",
      sidebarExtension: "Reception / Classroom Ext.:",
      sidebarAiBadge: "AI Assistant • Family Guide",
      sidebarAiTitle: "How to write an effective health report?",
      sidebarAiSubtitle: "To ensure your child's pharmacological safety in the classroom:",
      sidebarStep1: "Specify",
      sidebarStep1Bold: "exact dose",
      sidebarStep1End: "(ml/drops) and scheduled time.",
      sidebarStep2: "Indicate if",
      sidebarStep2Bold: "refrigeration",
      sidebarStep2End: "is required at reception.",
      sidebarStep3: "Always attach the",
      sidebarStep3Bold: "prescription or authorization",
      sidebarStep3End: "signed.",
      sidebarTemplateBtn: "Use Quick Health Template",
      sidebarNormTitle: "Pickup Times & Policies",
      sidebarNormDesc: "Any authorized adult other than the registered guardians must carry ID and be pre-registered in the portal.",
      sidebarEntryLabel: "Regular entry:",
      sidebarExitLabel: "Regular exit:",
    },
    calendarPage: {
      activitiesPanel: "Activities Panel",
      titleWord1: "Calendar",
      titleWord2: "&",
      titleWord3: "Activities",
      syncBtn: "Sync with Google Calendar / iCal",
      prevMonth: "Previous Month",
      nextMonth: "Next Month",
      viewMonth: "Month",
      viewWeek: "Week",
      viewAgenda: "Agenda",
      filterAll: "All events",
      filterSpecial: "Special Activities (2)",
      filterMeetings: "Parent Meetings (1)",
      filterWorkshops: "Stimulation Workshops (2)",
      months: [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
      ],
      daysOfWeek: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
      toastSync: "Syncing events with your iCal/Google calendar...",
      toastFilter: "Filtering activities",
      toastViewChanged: "View changed to mode: ",
      toastReminderScheduled: "Reminder scheduled",
      toastRsvpUnchecked: "Attendance temporarily unchecked",
      toastRsvpChecked: "Attendance confirmed for {name}!",
      toastDownloadingGuide: "Downloading Crazy Hat Pedagogical Guide (PDF 1.4MB)",
      toastAllMaterialsReady: "All weekly materials ready!",
      eventsThisMonth: "Events this month",
      upcomingActivities: "Upcoming Activities",
      chronologicalOrder: "Chronological order",
      noEvents: "No events found for this filter or selected month.",
      events: {
        evt1Title: "Phonemic Workshop & Stimulation",
        evt1Cat: "AMI Stimulation",
        evt1Desc: "Hands-on session for language development and phonological awareness.",
        evt2Title: "Spring Sensory Circuit",
        evt2Cat: "Playful / Garden",
        evt2Desc: "Outdoor activities for tactile exploration and gross motor skills.",
        evt3Title: "Advanced Phonemic Workshop",
        evt3Cat: "AMI Stimulation",
        evt3Desc: "Continuation of phonemic workshop focusing on articulation and vocabulary.",
        evt4Title: "Quarterly Family Meeting",
        evt4Cat: "Family Meeting",
        evt4Desc: "Presentation of academic and emotional progress reports for the period.",
        evt5Title: "Crazy Hat Day",
        evt5Cat: "Playful / Garden",
        evt5Desc: "Interactive themed celebration. Remember to bring recycled materials.",
        evt5Time: "All day"
      },
      upcomingSectionTitle: "Upcoming Featured Events & Activities",
      twoUpcomingBadge: "2 Upcoming",
      oneUpcomingBadge: "1 Upcoming",
      enrolledSubtitle: "enrolled in both",
      tuesday: "Tuesday",
      friday: "Friday",
      october2026: "October 2026",
      presentialBadge: "In-Person",
      virtualBadge: "Virtual via Google Meet",
      tagGarden: "Pedagogical Garden & Stimulation",
      tagNeuro: "Neurodevelopment Evaluation",
      locGarden: "Little Seeds Room & Montessori Garden Yard",
      locNeuro: "Guide {teacher} + Montekids Psychopedagogy",
      event1Title: "Crazy Hat Day & Community Garden",
      event1Desc: "Bring a hat decorated with homemade recycled materials for sensory stimulation, tactile motor skills, and planting seedlings in the garden with {name}.",
      event2Title: "Quarterly Family Meeting • Bi-monthly Report",
      event2Desc: "Joint personalized review of {name}'s fine motor progress, active language, and self-regulation according to the AMI rubric. Bi-monthly photo portfolio will be presented.",
      rsvpConfirmed: "✓ Attendance Confirmed",
      rsvpConfirm: "Confirm Attendance",
      downloadGuideBtn: "Download Activity Guide (PDF)",
      joinMeetBtn: "Join Virtual Session (Google Meet)",
      viewAgendaBtn: "View Order of the Day",
      pedagogicalSummaryBadge: "Pedagogical Summary for October",
      pedagogicalSummaryTitle: "18 Sensory Sessions Completed",
      pedagogicalSummaryDesc: "{name} attended 96% of guided classroom activities.",
      vsSept: "vs Sept",
      materialsTitle: "Pending Materials",
      materialsSubtitle: "Items needed for {classroom} and weekly sensory activities:",
      ofCount: "of",
      item1Text: "Extra change of clothes for water and soil sensory activities",
      item1Sub: "Delivered in locker #14",
      item2Text: "Recycled materials for Crazy Hat Day",
      item2Sub: "Pending for Tue Oct 31",
      item3Text: "1 portion of chopped fruit for shared snack",
      item3Sub: "Seedless grapes assigned",
      item4Text: "Water bottle labeled with thermal name tag",
      item4Sub: "Check before Monday",
      aiAssistantBadge: "Assistant",
      aiTipBadge: "Educational Tip",
      aiCardTitle: "How to make the Hat in 15 min?",
      aiCardDesc: "Use a paper plate or cereal box. Encourage your child to tear crepe paper and glue bottle caps: this stimulates tripod grasp and autonomy.",
      aiCardBtn: "View Step-by-Step",
      scheduleTitle: "Standard Schedule",
      scheduleRoutine: "Daily Routine",
      scheduleEntry: "Standard drop-off",
      scheduleEntryHours: "06:00 - 06:30 AM",
      scheduleSnack: "Sensory Snack",
      scheduleSnackHours: "10:00 - 10:30 AM",
      scheduleExit: "Standard pick-up",
      scheduleExitHours: "5:00 - 5:30 PM",
      delayQuestion: "Unexpected pick-up delay?",
      guidePrefix: "Guide",
      sendNoteBtn: "Send Note to Teacher",
      onlineTooltip: "Online",
      orderTitle: "Order of the Day",
      orderSubtitle: "Quarterly Meeting • October 27",
      orderStep1Title: "16:00 - 16:15: Welcome & Bi-monthly Focus",
      orderStep1Desc: "Introduction to Montessori observation methodology in Little Seeds Room.",
      orderStep2Title: "16:15 - 16:40: Individual Report Presentation",
      orderStep2Desc: "Review of {name}'s motor neurodevelopment, body schema, and interaction.",
      orderStep3Title: "16:40 - 17:00: Q&A with Psychopedagogy Team",
      orderStep3Desc: "Guidelines for home reinforcement and independent sleep stimulation.",
      orderUnderstoodBtn: "Understood",
      aiModalTitle: "Express Guide: Garden Hat",
      aiModalSubtitle: "Assistant",
      aiModalObjTitle: "Montessori Goal:",
      aiModalObjDesc: "Let your child decide on colors and textures without correcting symmetry to foster their autonomy.",
      aiModalStep1Title: "Minute 1 to 5: Structured Base",
      aiModalStep1Desc: "Cut out the base using a cardboard cone or biodegradable paper plate.",
      aiModalStep2Title: "Minute 5 to 10: Sensory Painting",
      aiModalStep2Desc: "Let {name} finger-paint freely with green and orange tones representing carrots and leaves.",
      aiModalStep3Title: "Minute 10 to 15: Tactile Texture",
      aiModalStep3Desc: "Attach dry twigs and fallen leaves using non-toxic water-based glue.",
      aiModalReadyBtn: "Ready to create!"
    },
    adminDashboard: {
      assignedClassroom: "Your Assigned Classroom",
      exportReport: "Export Report",
      newEvaluation: "+ New Evaluation",
      activeCensus: "Active Census",
      registeredChildren: "Registered Children",
      students: "Students",
      roomCapacity: "Room capacity: 96%",
      freeSpot: "1 spot available",
      starsEconomy: "Star Economy",
      accumulatedStars: "Accumulated Stars",
      totalStars: "Total Stars",
      noStarsYet: "No stars yet",
      gamesActivity: "Games Activity",
      sessionsCompleted: "Completed Sessions",
      totalGames: "Total Games",
      noGamesYet: "No games played yet",
      longitudinalPanel: "Longitudinal Panel",
      metricsTitle: "Development & Progression Metrics",
      last6Months: "Last 6 Months",
      quarter: "Quarter",
      annual: "Annual",
      psychomotorSensory: "Psychomotor & Sensory",
      cognitiveLanguage: "Cognitive & Language",
      socioemotional: "Socio-emotional",
      attendanceRecord: "Attendance Record",
      takeAttendance: "TAKE ATTENDANCE & REVIEW HISTORY",
      prevDay: "◄ Previous",
      today: "Today",
      nextDay: "Next ►",
      showCalendar: "🗓️ Show Calendar",
      hideCalendar: "🗓️ Hide Calendar",
      prevMonth: "‹ Prev Month",
      nextMonth: "Next Month ›",
      tutor: "Tutor:",
      present: "Present",
      absent: "Absent",
      noStudentsInClass: "No students registered in this classroom.",
      attendanceSummary: "Attendance Summary",
      presentCountLabel: "present",
      absentCountLabel: "absent",
      montessoriTipTitle: "MONTESSORI TIP OF THE DAY",
      montessoriTipText: '"Any unnecessary help is an obstacle to child development." Allow 3 autonomous attempts before assisting with buttoning.',
      teachingSection: "TEACHING SECTION",
      studentsManagementTitle: "Student Management & Records",
      studentsManagementSubtitle: "Review child info, send log notes, and assign activities or materials.",
      searchStudentPlaceholder: "Search student or tutor...",
      noStudentsFound: "No students found matching the selected criteria.",
      tutorLabel: "Tutor:",
      genderLabel: "GENDER",
      girl: "👧 Girl",
      boy: "👦 Boy",
      ageLabel: "AGE",
      assignedClassroomLabel: "ASSIGNED CLASSROOM",
      unassignedClassroom: "Unassigned classroom",
      sendNoteBtn: "💬 Send Note to Log",
      assignTaskBtn: "📋 Assign Activity or Material",
      planningHeader: "EDUCATIONAL PLANNING & CALENDAR",
      curriculumTitle: "Curriculum Plan for",
      allClassrooms: "All Classrooms",
      curriculumSubtitle: "Schedule topics and activities for each date. Synchronized automatically with family calendars.",
      searchCurriculumPlaceholder: "Search in curriculum plan...",
      addCurriculumBtn: "+ Schedule Activity",
      noCurriculumEvents: "No activities scheduled in the curriculum plan. Click \"+ Schedule Activity\" to add one.",
      deleteEventTitle: "Delete from curriculum plan",
      deleteBtn: "Delete",
      reportsHeader: "FAMILY ATTENTION & MESSAGING",
      reportsTitle: "Reports & Comments for",
      reportsSubtitle: "Review health notices, permissions, or notes sent by tutors and reply directly to their messages.",
      totalMessages: "Total Messages",
      filterByTutor: "👨‍👩‍👧‍👦 Filter by Student Tutor:",
      allTutors: "🌐 All Tutors",
      noReportsForTutor: "No reports or messages found for the selected tutor.",
      pendingResponse: "Pending teacher response",
      replyToTutor: "Reply to Tutor",
      modifyReply: "Modify Reply",
      noteModalTitle: "💬 Send Note to Log",
      targetStudentLabel: "Recipient student:",
      writeNoteLabel: "Write your pedagogical observation or note:",
      notePlaceholder: "Ex: Enthusiastically explored sensory material and actively participated in the routine...",
      sendToLogBtn: "Send to Log",
      cancelBtn: "Cancel",
      taskModalTitle: "📋 Assign Activity or Material",
      assignToLabel: "Assign to:",
      taskTitleLabel: "Material or Task Title:",
      taskTitlePlaceholder: "Ex: Recycled materials for Crazy Hat...",
      taskSubtitleLabel: "Additional Note / Instruction:",
      taskSubtitlePlaceholder: "Ex: Due by Tue Oct 31",
      taskIconLabel: "Representative Icon:",
      assignToCalendarBtn: "Assign to Calendar",
      currModalTitle: "📅 Schedule Curriculum Activity",
      currTitleLabel: "Activity or Topic Title:",
      currTitlePlaceholder: "Ex: Plastic Expression & Textures Workshop...",
      currDateLabel: "Date:",
      currTimeLabel: "Time:",
      currTimePlaceholder: "Ex: 09:00 AM - 10:30 AM",
      currCategoryLabel: "Area / Category:",
      catWorkshops: "AMI Stimulation (Workshops)",
      catSpecial: "Playful / Garden / Special Activities",
      catMeetings: "Family Meeting / Institutional",
      catAcademic: "Academic Area / Expression",
      currDescLabel: "Pedagogical Description or Observations:",
      currDescPlaceholder: "Detail pedagogical goals or what students will do that day...",
      saveToCalendarBtn: "Save to Calendar",
      replyModalTitle: "💬 Reply to",
      tutorInquiryLabel: "Family Inquiry:",
      replyStatusLabel: "Response Status Tag:",
      optAttended: "✓ Attended / Acknowledged",
      optDose: "💊 Dose or Medication Administered",
      optPermission: "⏰ Schedule / Permission Authorized",
      optObs: "📝 Recorded in File",
      replyMessageLabel: "Response or Message for Tutor:",
      replyPlaceholder: "Type response to be displayed on family dashboard...",
      sendReplyBtn: "Send Reply",
      nav: {
        dashboard: "Dashboard",
        students: "Students",
        curriculum: "Curriculum Plan",
        evaluations: "Evaluations",
        reports: "Reports"
      }
    }
  },
  zh: {
    nav: {
      home: '首页',
      philosophy: '教学理念',
      classrooms: '班级空间',
      reviews: '家长评价',
      contact: '位置与联系',
      aiAssistant: 'AI 助手',
      login: '登录',
      backToHome: '返回首页',
      changeTextSize: '更改字体大小',
      changeTheme: '切换主题',
      colorblind: '色盲模式',
      language: '语言'
    },
    cancionesPage: {
      badgeSection: '韵律角',
      badgeCategory: '教育音乐视频',
      title: '儿童动画歌曲',
      playingBadge: '正在播放视频',
      starsReward: '完整演唱可得 +5 颗星',
      playVideo: '播放视频',
      pauseVideo: '暂停视频',
      restartVideo: '重新开始',
      speedLabel: '播放速度:',
      speedSlow: '0.8x 慢速',
      speedNormal: '1.0x 正常',
      speedFast: '1.2x 快速',
      catalogTitle: '选择你最喜欢的歌曲！',
      seeAll: '查看全部',
      dailyMissionTitle: '每日任务 • 专心倾听者',
      dailyMissionLevel: '探索者级别',
      dailyMissionBannerTitle: '演唱并倾听歌曲，赢取更多金星！',
      dailyMissionBannerDesc: '每播放一首歌曲，都能帮助探索者在享受音乐的同时关联声音与词汇。',
      goalOfDay: '每日目标',
      remainingSongs: '首歌曲待听！',
      bonusReward: '+10 ★ 奖励'
    },
    hero: {
      badge: '早期潜能开发中心',
      titleStart: '在这里，让',
      wordLearn: '学习',
      and: '与',
      wordGrow: '成长',
      isAn: '成为一场',
      wordAdventure: '奇妙',
      wordMagical: '冒险',
      desc: '我们为婴幼儿提供早期教育、运动发展和主动学习，让他们在安全、温暖和充满探索的环境中快乐成长。',
      btnWhatsapp: '通过 WhatsApp 咨询',
      btnLocation: '查看校区位置',
      sensoryTitle: '感官探索课程',
      sensoryDesc: '精细动作与身体协调',
      live: '进行中'
    },
    philosophy: {
      badge: 'AMI 国际蒙台梭利教学法',
      title: '我们的教育哲学与教学体系',
      desc: '尊重敏感期、启发天生好奇心并促进全面神经发育的三大教育基石。',
      c1Badge: '360° 全维发展',
      c1Title: '全面早期潜能开发 🧠',
      c1Desc: '借助蒙台梭利教具，将认知、动作、感官与社交语言发展有机融合。',
      c1Footer: '感觉统合探索',
      c2Badge: '家校紧密互联',
      c2Title: '家庭成长贴心陪伴 📱',
      c2Desc: '家长专属空间：实时动态记录、每日成就照片墙与导师直通互动。',
      c2Footer: 'Montekids 家长端 App',
      c3Badge: '智慧教育赋能',
      c3Title: 'AI 智能成长追踪 🌟',
      c3Desc: '资深教师团队与自适应数据分析协同，为每位孩子量身定制专属动态方案。',
      c3Footer: '定制化启蒙方案'
    },
    programs: {
      badge: '班级课程体系',
      title: '我们的特色教室与成长阶段',
      desc: '根据儿童人体工学精心配备适龄桌椅与自主纠错型蒙氏教具空间。',
      cycle: '2027 新学年',
      openEnrollment: '开放学位申请',
      consultBtn: '咨询学位',
      r1Age: '2 至 3 岁',
      r1Title: '萌芽班 (Semillitas)',
      r1Desc: '深度感官启蒙、早期语言萌发、探索性大动作训练与安全依恋建立。',
      r1Ratio: '师生比 1:5',
      r1Cap: '每班上限 10 名儿童',
      r1Sched: '上午半日 (8:30 - 12:30)',
      r1Assigned: '已录 80% 学位',
      r1Free: '仅剩 2 个名额',
      r2Age: '3 至 4 岁',
      r2Title: '探索班 (Exploradores)',
      r2Desc: '主动语言表达、协作性社交、前逻辑思维启蒙及日常生活自理能力。',
      r2Ratio: '师生比 1:7',
      r2Cap: '每班上限 14 名儿童',
      r2Sched: '全日制或半日制',
      r2Assigned: '已录 65% 学位',
      r2Free: '剩余 5 个名额',
      r3Age: '4 至 5 岁',
      r3Title: '创想班 (Creadores)',
      r3Desc: '多感官拼音读写准备、精细动作熟练、科学探究实验与启发式游戏挑战。',
      r3Ratio: '师生比 1:8',
      r3Cap: '每班上限 16 名儿童',
      r3Sched: '全日制 (8:30 - 16:30)',
      r3Assigned: '已录 88% 学位',
      r3Free: '即将满员',
      ratioLabel: '师资配置:',
      capLabel: '班级容量:',
      schedLabel: '作息时间:'
    },
    IMAS: {
      badge: 'IMAS 助学福利',
      title: '您的孩子是否享有 IMAS 托育补贴福利？',
      desc: '如果您的孩子目前就读于其他日托中心，您可以申请转入 MONTEKIDS。我们的专业团队将在整个流程中为您提供协助与指导。',
      cycle: '2027 新学年',
      openEnrollment: '开放学位申请',
      consultBtn: '咨询学位',
      r1Age: '步骤 1',
      r1Title: '填写 IMAS 在线服务申请表，如实提交您的个人信息、身份证号以及幼儿的相关资料。',
      r1Desc: '',
      r1Ratio: '',
      r1Cap: '',
      r1Sched: '',
      r1Assigned: '',
      r1Free: '仅剩 2 个名额',
      r2Age: '步骤 2',
      r2Title: '在申请表的备注或详情栏中说明您正在申请转托幼儿关爱与发展中心 (CECUDI) 或托育网络 (Red de Cuido)，并注明转托原因与心仪的新中心。',
      r2Desc: '',
      r2Ratio: '',
      r2Cap: '',
      r2Sched: '',
      r2Assigned: '已录 65% 学位',
      r2Free: '剩余 5 个名额',
      r3Age: '步骤 3',
      r3Title: '提交申请并耐心等待社工与您联系，核实变更信息并确认新校区的学位空缺情况。',
      r3Desc: '',
      r3Ratio: '',
      r3Cap: '',
      r3Sched: '',
      r3Assigned: '',
      r3Free: '即将满员',
      ratioLabel: '师资配置:',
      capLabel: '班级容量:',
      schedLabel: '作息时间:'
    },
    testimonials: {
      badge: '社群信赖与认可',
      title: 'Montekids 幸福家庭分享',
      desc: '来自信赖我们陪伴的真实家长心声。',
      t1Text: '“关怀非常细致，教学方法极佳。Mateo 在语言、独立性和运动方面进步飞速。而且家长平台每天都能清晰看到他的每一个微小突破。”',
      t1Author: 'Valeria Quirós',
      t1Role: 'Mateo 妈妈 (探索班)',
      t2Text: '“园所环境充满爱意与启迪。老师专业素养极高，因材施教的理念让 Sofi 充满了自信与安全感。”',
      t2Author: 'Carlos Mendoza',
      t2Role: 'Sofía 爸爸 (创想班)',
      c1Val: '+150',
      c1Title: '快乐儿童',
      c1Desc: '悉心温暖陪伴',
      c2Val: '12',
      c2Title: '年卓越办学',
      c2Desc: '国际前沿教育',
      c3Val: '100%',
      c3Title: '家庭连接率',
      c3Desc: 'App 实时动态',
      c4Val: '5/5 ★',
      c4Title: '综合评分',
      c4Desc: '权威家校满意度'
    },
    location: {
      badge: '校区地址与直达联系',
      title: '欢迎探校与垂询',
      desc: '想要实地参观校区或咨询学位？欢迎随时致电、留言或亲临校园。',
      hoursBadge: '服务时间：6:00 AM - 6:00 PM',
      hqTitle: 'Montekids 核心校区',
      address: '蓬塔雷纳斯省，埃尔罗布莱 5A 大道，60101',
      scheduleLabel: '开放时间:',
      scheduleVal: '周一至周五: 6:00 AM - 6:00 PM',
      phoneLabel: '联系电话:',
      emailLabel: '电子邮箱:',
      btnWhatsapp: '通过 WhatsApp 咨询'
    },
    cta: {
      badge: '2027 学位申请',
      title: '准备好开启孩子的美好未来了吗？',
      desc: '2027 学年学位有限。即刻预约线下探校或一对一线上咨询，让我们将每次探索都变成难忘的成长记忆。',
      btnChat: '通过 WhatsApp 咨询',
      f1: '即时响应',
      f2: '40分钟定制化探校体验'
    },
    footer: {
      desc: '蒙台梭利早期儿童成长与全面潜能开发中心。从人生的最初脚步起，守护天生好奇与自主。',
      certAmi: '国际 AMI 权威认证',
      explore: '探索发现',
      linkPhil: '教育哲学',
      linkClass: '班级空间',
      linkRev: '家长评价',
      linkLoc: '校区与联系',
      contact: '联系我们',
      locPuntarenas: '蓬塔雷纳斯，埃尔罗布莱',
      hours: '营业时间: 周一至周五 06:00 - 18:00',
      copy: '© 2026 Montekids 早期儿童与潜能开发中心。版权所有。',
      privacy: '隐私政策',
      protocol: '儿童关怀安全准则'
    },
    auth: {
      tabLogin: '登录',
      tabRegister: '注册账户',
      certBar: 'AMI 认证教育平台 • 校园级生物特征安全加密',
      communityBar: 'Montekids 社群 • 超 1,400 个家庭信赖互联',
      montessoriBadge: '蒙台梭利数字化教学体系',
      heroTitle: '全程护航孩子的每一步成长 🌟',
      heroDesc: '随时查看每日活动报告、感官探索精彩照片、课堂童谣音频，并与带班导师一对一即时交流。',
      heroF1: '实时动态成长记录',
      heroF2: '运动机能与语言里程碑跟踪',
      heroF3: '安全荣誉勋章与微奖励空间',
      trust1Title: '铜墙铁壁般的隐私保护',
      trust1Desc: '严格符合 COPPA 与 GDPR-K 儿童安全规范',
      trust2Title: '国际 AMI 协会',
      trust2Desc: '纯正蒙台梭利教学法验证',
      trust3Title: '全天候家庭支持',
      trust3Desc: '24/7 专业教育咨询帮助台',
      schoolCycle: '2025 学年 • 春季学期',
      loginWord1: '欢迎',
      loginWord2: '回来！',
      loginWord3: '',
      loginSubtitle: '登录您的账户，继续实时关注您的小探险家并查看他们的感官成长记录。',
      googleAuth: '使用 Google Workspace 校园账号登录',
      orDivider: '或使用邮箱密码登录',
      emailLabel: '注册家长 / 监护人邮箱',
      emailPlaceholder: '例如: mama.mateo@email.com',
      passwordLabel: '密码',
      passwordPlaceholder: '••••••••',
      forgotPassword: '忘记密码？',
      rememberMe: '在此设备上保持登录 30 天',
      submitLogin: '进入虚拟课堂',
      noAccountText: '还没有为您的小朋友注册账号？',
      registerLink: '在此注册 ✨',
      regSchoolCycle: '家庭注册入读 • 2025 学年',
      regWord1: '创建',
      regWord2: '您的',
      regWord3: '家庭',
      regWord4: '账户',
      regWord5: '',
      regSubtitle: '安全绑定课堂直通权限以及您孩子在 Montekids 的专属成长档案。',
      regNameLabel: '家长或监护人全名',
      regNamePlaceholder: '例如: Valeria Quirós Fernández',
      regEmailLabel: '常用联系邮箱',
      regEmailPlaceholder: 'your.email@example.com',
      regCodeLabel: '班级 / 学员认证码',
      regCodeBadge: '由前台教务提供',
      regCodePlaceholder: '例如: MK-2025-EXPLO-88',
      createPassLabel: '创建安全密码',
      createPassPlaceholder: '至少 8 位字符',
      termsText1: '我同意',
      termsLink: '服务条款',
      termsText2: '并授权依照',
      privacyLink: 'AMI 政策处理',
      submitRegister: '创建家庭账户 ✨',
      haveAccountText: '已经拥有活跃的监护人账户？',
      loginLink: '在此登录 🔒',
      passNone: '无密码',
      passWeak: '较弱',
      passGood: '良好',
      passStrong: '强且安全',
      invalidCredentials: "邮箱或密码错误，请检查您的信息。",
      connectionError: "无法连接到身份验证服务器。",
      loggingIn: "登录中...",
      loginButton: "登录",
    },
    ai: {
      title: 'AI 智能助手 🤖',
      online: '在线随时为您解答',
      welcome: '您好！我是 Montekids AI 助手。请问有什么可以帮您？（例如：课程时间、校区位置或 WhatsApp 咨询）',
      reply: '感谢您的提问！我们的教学团队和学位咨询均已就绪。是否希望通过 WhatsApp 直接联系我们？',
      placeholder: '请输入您的问题...'
    },
    forgotPassword: {
      backToLogin: "返回登录",
      title1: "忘记",
      title2: "您的",
      title3: "密码？",
      desc: "请输入与您的家长或监护人账户关联的电子邮箱，我们将立即向您发送密码重置说明。",
      emailLabel: "已注册的电子邮箱",
      emailPlaceholder: "例如: mama.mateo@email.com",
      expirationNotice: "出于严格的校园安全及 COPPA 协议下的儿童保护规定，验证链接将在 15 分钟内失效。",
      submitBtn: "发送重置链接",
      viewMode: "视图:",
      formView: "表单",
      sentView: "已发送",
      errorCode: "验证码不正确。",
      panelBadge: "蒙台梭利数字化教学体系",
      panelTitle: "守护您孩子的个人信息安全 🛡️",
      panelDesc: "在 Montekids，我们依照最高标准的教育规范，妥善保护您孩子的感官记录、照片及成长评估。",
      card1Title: "已开启两步验证",
      card1Desc: "任何登录凭证的变更都将立即通知主监护人。",
      card2Title: "教务处直接支持",
      card2Desc: "如果您无法访问邮箱，我们的团队将通过线下安全验证您的身份。",
      card3Title: "一次性加密令牌",
      card3Desc: "确保密码重置仅由已注册的账户所有者操作。",
      noAccess: "无法访问此邮箱？",
      contactSchool: "联系教务处",
      encryptionLabel: "加密",
      sessionIdLabel: "会话 ID",
      successTitle: "找回密码邮件已发送！",
      successInstructions: "我们已将重置说明发送至：",
      resendAvailableIn: "可在...后重发邮件",
      resendNow: "重新发送验证邮件！",
      verifyAnotherEmail: "验证其他邮箱",
      goToLogin: "前往登录页面",
      validateAndLogin: "验证并登录",
      attemptsUsed: "已使用尝试次数",
      incompleteCodeError: "请输入完整的6位验证码。",
    },
    parentDashboard: {
      header: {
        badge: "综合成长监测面板",
        title1: "日常",
        title2: "记录",
        title3: "与家庭",
        title4: "成长",
        subtitle: "实时监测感官、认知发展及日常活动：",
        reportsBtn: "我的反馈与便签"
      },
      metrics: {
        fineMotor: "精细动作技能",
        physicalArea: "身体发展",
        fineMotorBadge: "🌟 抓握能力出色！",
        fineMotorDesc: "能够独立完成拼插，并熟练使用符合人体工程学的勺子转移种子。",
        language: "语言与表达",
        communicationArea: "沟通交流",
        languageBadge: "💬 掌握 6 个新词汇",
        languageDesc: "流利发音 /M/、/P/ 声母，并能说出由 4 个词组成的连贯句子。",
        sensory: "感官与认知",
        cognitionArea: "认知发展",
        sensoryBadge: "🧩 模式认知持续进步",
        sensoryDesc: "能按颜色识别序列，并非常专注地探索天然材质纹理盒。"
      },
      timeline: {
        headerTitle: "Mateo 的每日日志",
        today: "今天，2026年10月28日",
        inSession: "上午活动中",
        completedSuccess: "顺利完成",
        completedAt: "完成于 11:15 AM",
        inProgress: "进行中",
        teacherName: "Karina 老师",
        act1Title: "语音与童谣工作坊",
        act1Area: "语言领域",
        act1Time: "09:15 AM - 10:00 AM",
        act1Note: "“Mateo 非常高兴地参与了在押韵车厢中识别字母 M 的活动。和 Sofía、Lucas 一起唱歌时展现出了极大的热情。”",
        act2Title: "纹理环路与嗅觉刺激",
        act2Area: "感官领域",
        act2Time: "10:30 AM - 11:15 AM",
        act2Note: "“探索了装有薰衣草和种子的托盘，没有任何触觉排斥。他的耐受力和专注表现非常优秀。”",
        act3Title: "合作种植与健康加餐",
        act3Desc: "时间: 11:45 AM - 12:30 PM • 采摘樱桃番茄与洗手环节。",
        formTitle: "向托儿所发送报告或咨询",
        formDesc: "直接与 Karina 老师或前台团队沟通。",
        cat1: "健康咨询",
        cat2: "时间 / 接送通知",
        cat3: "教学咨询",
        placeholder: "例如：明天 11:30 AM 需要带孩子看儿科医生，提前接走...",
        defaultMsg: "明天 11:30 AM 因预约儿科医生需要提前接走孩子。",
        sendBtn: "发送至班级",
        successMsg: "消息已发送给 Karina 老师！将在休息时间通知阅读。"
      },
      sidebar: {
        achievementsTitle: "近期成就",
        levelBadge: "幼苗 2 级",
        badge1Title: "黄金抓握",
        badge1Desc: "精细动作与自主能力",
        badge2Title: "明星阅读者",
        badge2Desc: "识别 5 个发音",
        badge3Title: "合作小伙伴",
        badge3Desc: "整理并分享器材",
        viewAllBadges: "查看所有勋章 (8) →",
        aiBadge: "💡 AI 每周建议",
        aiTip: "“给 Mateo 家长的建议：为了巩固在精细动作上达到的 85% 进度，建议在晚餐前安排 10 分钟的拼插游戏或捏橡皮泥活动。”",
        aiActionBtn: "查看 3 个亲子互动游戏 🏡",
        remindersTitle: "近期提醒",
        rem1Title: "季度家长会",
        rem1Desc: "16:00 • 线上会议",
        rem2Title: "疯狂帽子与园艺日",
        rem2Desc: "请携带环保手工帽子",
        syncCalendar: "同步至谷歌日历",
        teacherContactTitle: "班级联系人",
        teacherRole: "Semillitas 班级 AMI 首席引导员",
        teacherAvailability: "休息时间在线 (13:00 - 14:00)",
        whatsappBtn: "官方 WhatsApp 联系"
      },
      hero: {
        greeting: "您好， 家长",
        summaryStart: "这是",
        summaryMiddle: "今天在",
        summaryEnd: "的成长日报。",
        presentBadge: "今日出勤",
        ageBadge: "满 3 岁",
        classroomBadge: "萌芽班 (Semillitas)",
        attendanceBadge: "签到时间: 08:15 AM (人脸识别)",
        teacherBadge: "带班导师: Karina S.",
        sendNoteBtn: "+ 给老师发送留言",
        yearsOld: "岁",
        guide: "带班导师: "
      },
      nav: {
        myChild: "我的孩子",
        reports: "我的反馈/报告",
        calendar: "活动日程表",
        games: "游戏世界",
        backToDashboard: "家长中心",
        backToDashboardShort: "家长中心",
        goToGames: "前往游戏",
        aiAssistant: "AI 助手",
        userRole: "Mateo 的妈妈"
      },
      profileSettings: {
        title: "个人资料设置",
        subtitle: "更新您的信息和头像",
        photoLabel: "头像照片",
        quickOptions: "快捷选项或姓名缩写：",
        initialsBtn: "姓名缩写",
        uploadDeviceBtn: "从设备选择照片",
        changePhotoHover: "从设备更换照片",
        urlPlaceholder: "或粘贴网络照片网址 (https://...)",
        nameLabel: "全名",
        namePlaceholder: "您的全名...",
        emailLabel: "电子邮箱",
        emailPlaceholder: "example@email.com",
        cancelBtn: "取消",
        saveBtn: "保存修改",
        savingBtn: "正在保存...",
        successMessage: "个人资料更新成功！",
        localSuccessMessage: "已保存在本地！",
        errorNameRequired: "姓名不能为空。",
        errorEmailRequired: "电子邮箱不能为空。",
        errorInvalidImage: "请选择有效的图片文件 (JPG, PNG, WEBP 等)。",
        errorImageSize: "选择的图片大小不能超过 5MB。",
        settingsTooltip: "个人资料设置"
      },
    },
    reportsPage: {
      syncedWith: "已同步至",
      pageTitle1: "沟通",
      pageTitle2: "与",
      pageTitle3: "报告",
      pageTitle4: "收件箱",
      pageTitle5: "",
      pageSubtitle: "已发送消息及回复记录来自",
      pageSubtitleMid: "•",
      composeBtn: "撰写新消息",
      filterAll: "全部",
      filterHealth: "健康咨询",
      filterSchedule: "接送/时间通知",
      filterPedagogical: "教学观察",
      composerTitle: "撰写新消息 / 报告",
      composerSubtitle: "向班级引导员发送直接通知。",
      categoryLabel: "报告类别",
      catHealth: "健康咨询",
      catSchedule: "时间通知",
      catPedagogical: "教学观察",
      catHealthFull: "健康咨询",
      catScheduleFull: "接送 / 时间通知",
      catPedagogicalFull: "教学观察",
      subjectLabel: "主题或标题",
      subjectPlaceholder: "例如: 晨间用药管理...",
      messageLabel: "消息或说明",
      messagePlaceholder: "在此填写详细信息...",
      attachBtn: "附上处方或文件",
      sendBtn: "发送报告",
      sentJustNow: "刚刚发送",
      historyTitle: "最近消息记录",
      sortRecent: "最新优先",
      sortPending: "待回复",
      sortCategory: "按类别",
      statusConfirmed: "已确认",
      statusPending: "待处理",
      emptyTitle: "您还没有任何报告或消息。",
      emptyDesc: "使用上方表单向老师发送您的第一条咨询或报告。",
      deleteTitle: "在收到回复前删除此消息",
      signedLabel: "由护理人员和引导员数字签署",
      sidebarContactTitle: "班级直接联系",
      sidebarOnlineTitle: "在教室在线",
      sidebarBreakHours: "家长互动时间: 13:00 - 14:00",
      sidebarExtension: "前台 / 班级分机:",
      sidebarAiBadge: "AI 助手 • 家庭指南",
      sidebarAiTitle: "如何撰写有效的健康报告？",
      sidebarAiSubtitle: "为确保孩子在教室的用药安全:",
      sidebarStep1: "注明",
      sidebarStep1Bold: "精确剂量",
      sidebarStep1End: "(ml/滴) 及服用时间。",
      sidebarStep2: "说明是否需要在前台",
      sidebarStep2Bold: "冷藏保存",
      sidebarStep2End: "。",
      sidebarStep3: "始终随附",
      sidebarStep3Bold: "处方或授权书",
      sidebarStep3End: "(已签署)。",
      sidebarTemplateBtn: "使用健康快速模板",
      sidebarNormTitle: "接送时间与规定",
      sidebarNormDesc: "除注册监护人以外的任何授权成人必须携带身份证，并事先在门户网站中登记。",
      sidebarEntryLabel: "常规入园时间:",
      sidebarExitLabel: "常规离园时间:",
    },
    calendarPage: {
      activitiesPanel: "活动中心",
      titleWord1: "日历",
      titleWord2: "与",
      titleWord3: "活动",
      syncBtn: "同步至 Google 日历 / iCal",
      prevMonth: "上个月",
      nextMonth: "下个月",
      viewMonth: "月",
      viewWeek: "周",
      viewAgenda: "日程",
      filterAll: "全部活动",
      filterSpecial: "特色活动 (2)",
      filterMeetings: "家长会 (1)",
      filterWorkshops: "启智工坊 (2)",
      months: [
        "一月", "二月", "三月", "四月", "五月", "六月",
        "七月", "八月", "九月", "十月", "十一月", "十二月"
      ],
      daysOfWeek: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
      toastSync: "正在与您的 iCal/Google 日历同步...",
      toastFilter: "正在筛选活动",
      toastViewChanged: "视图模式已切换为: ",
      toastReminderScheduled: "已添加日程提醒",
      toastRsvpUnchecked: "已暂时取消出席登记",
      toastRsvpChecked: "已成功确认 {name} 出席！",
      toastDownloadingGuide: "正在下载疯狂帽子节教学指南 (PDF 1.4MB)",
      toastAllMaterialsReady: "本周所有学习用品已齐备！",
      eventsThisMonth: "本月活动数",
      upcomingActivities: "近期重点活动",
      chronologicalOrder: "按时间先后排序",
      noEvents: "当前筛选条件或所选月份暂无活动。",
      events: {
        evt1Title: "语音感知与早期启智工坊",
        evt1Cat: "AMI 潜能启智",
        evt1Desc: "语言发展与语音意识的动手实践课程。",
        evt2Title: "春季感官探索环路",
        evt2Cat: "趣玩 / 种植园",
        evt2Desc: "户外触觉探索与大肌肉运动技能发展活动。",
        evt3Title: "进阶语音启蒙工作坊",
        evt3Cat: "AMI 潜能启智",
        evt3Desc: "侧重于正确发音与词汇拓展的语音工坊进阶篇。",
        evt4Title: "季度家长交流会",
        evt4Cat: "家长会",
        evt4Desc: "展示本阶段学术与情感成长进步报告。",
        evt5Title: "疯狂帽子趣味日",
        evt5Cat: "趣玩 / 种植园",
        evt5Desc: "互动主题庆祝活动，请记得携带环保可回收手工材料。",
        evt5Time: "全天活动"
      },
      upcomingSectionTitle: "近期重点活动与日程",
      twoUpcomingBadge: "2 项待参加",
      oneUpcomingBadge: "1 项待参加",
      enrolledSubtitle: "已报名参加两项活动",
      tuesday: "周二",
      friday: "周五",
      october2026: "2026年 10月",
      presentialBadge: "线下进行",
      virtualBadge: "Google Meet 线上会议",
      tagGarden: "教学小菜园与感官启智",
      tagNeuro: "神经发育评估",
      locGarden: "萌芽班与蒙台梭利小菜园庭院",
      locNeuro: "带班导师 {teacher} + Montekids 心理教育团队",
      event1Title: "疯狂帽子节与社区菜园实践",
      event1Desc: "携带在家用环保材料制作的创意帽子，与 {name} 一同参与感官刺激、手部触觉锻炼和小菜园幼苗种植活动。",
      event2Title: "季度家庭会议 • 双月成长报告",
      event2Desc: "依据 AMI 评估准则，联合审阅 {name} 在精细动作、主动语言及自我调节能力的发展，并展示双月照片成长集。",
      rsvpConfirmed: "✓ 已确认 出席",
      rsvpConfirm: "确认出席",
      downloadGuideBtn: "下载活动指南 (PDF)",
      joinMeetBtn: "加入在线会议 (Google Meet)",
      viewAgendaBtn: "查看会议议程",
      pedagogicalSummaryBadge: "十月教学成果简报",
      pedagogicalSummaryTitle: "已完成 18 次感官启智课程",
      pedagogicalSummaryDesc: "{name} 参与了班级 96% 的引导式活动。",
      vsSept: "环比九月",
      materialsTitle: "待准备学习材料",
      materialsSubtitle: "{classroom} 本周感官与日常活动所需物品：",
      ofCount: "/",
      item1Text: "水与泥土感官探索用备换衣物",
      item1Sub: "已存放于 14 号储物柜",
      item2Text: "疯狂帽子节所需可回收手工材料",
      item2Sub: "待备（10月31日 周二）",
      item3Text: "1 份分享点心用水果切片",
      item3Sub: "已分配：无籽葡萄",
      item4Text: "贴有隔热姓名标签的水杯",
      item4Sub: "请在周一前检查",
      aiAssistantBadge: "AI 助手",
      aiTipBadge: "育儿小妙招",
      aiCardTitle: "如何在 15 分钟内完成创意帽子？",
      aiCardDesc: "使用纸盘或麦片包装盒。鼓励孩子撕碎皱纹纸并粘贴塑料瓶盖：该活动可充分锻炼三指捏握反射并培养独立性。",
      aiCardBtn: "查看详细制作步骤",
      scheduleTitle: "常规日程表",
      scheduleRoutine: "每日作息",
      scheduleEntry: "常规入园",
      scheduleEntryHours: "06:00 - 06:30 AM",
      scheduleSnack: "感官晨点",
      scheduleSnackHours: "10:00 - 10:30 AM",
      scheduleExit: "常规离园",
      scheduleExitHours: "5:00 - 5:30 PM",
      delayQuestion: "接送可能临时延误？",
      guidePrefix: "引导员",
      sendNoteBtn: "给老师发送留言",
      onlineTooltip: "在线",
      orderTitle: "会议议程",
      orderSubtitle: "季度家长会 • 10月27日",
      orderStep1Title: "16:00 - 16:15: 欢迎致辞与双月重点",
      orderStep1Desc: "介绍萌芽班蒙台梭利日常观察方法与教学理念。",
      orderStep2Title: "16:15 - 16:40: 个性化成长报告展示",
      orderStep2Desc: "深入分析 {name} 的动作神经发育、身体图式与社交互动。",
      orderStep3Title: "16:40 - 17:00: 心理教育顾问答疑时间",
      orderStep3Desc: "针对家庭辅导与独立睡眠培养的专业建议。",
      orderUnderstoodBtn: "已知晓",
      aiModalTitle: "快速指南：菜园创意帽子",
      aiModalSubtitle: "AI 助手",
      aiModalObjTitle: "蒙台梭利教育目标：",
      aiModalObjDesc: "让孩子自主挑选颜色与材质，避免强求对称，以充分建立自信与自主性。",
      aiModalStep1Title: "第 1 至 5 分钟: 搭建基础结构",
      aiModalStep1Desc: "使用纸质锥筒或可降解环保纸盘裁剪出帽子基底。",
      aiModalStep2Title: "第 5 至 10 分钟: 感官色彩涂绘",
      aiModalStep2Desc: "让 {name} 用小手指自由蘸取绿色与橙色颜料，模拟胡萝卜与绿叶。",
      aiModalStep3Title: "第 10 至 15 分钟: 触觉质感装饰",
      aiModalStep3Desc: "使用环保无毒水性胶水粘贴枯小树枝与公园落叶。",
      aiModalReadyBtn: "准备开始动手制作！"
    },
    adminDashboard: {
      assignedClassroom: "您分配的班级",
      exportReport: "导出报告",
      newEvaluation: "+ 新建评估",
      activeCensus: "班级学员",
      registeredChildren: "已登记儿童",
      students: "学员",
      roomCapacity: "教室容量: 96%",
      freeSpot: "余 1 个名额",
      starsEconomy: "星星奖励机制",
      accumulatedStars: "累计获得星星",
      totalStars: "星星总数",
      noStarsYet: "暂无星星",
      gamesActivity: "游戏互动情况",
      sessionsCompleted: "已完成游戏场次",
      totalGames: "游戏总场次",
      noGamesYet: "暂无游戏记录",
      longitudinalPanel: "纵向发展面板",
      metricsTitle: "儿童发展与成长进阶指标",
      last6Months: "近 6 个月",
      quarter: "本季度",
      annual: "本年度",
      psychomotorSensory: "大动作与感官发育",
      cognitiveLanguage: "认知与语言表达",
      socioemotional: "社交与情感沟通",
      attendanceRecord: "考勤与点名记录",
      takeAttendance: "每日点名与历史考勤",
      prevDay: "◄ 前一天",
      today: "今天",
      nextDay: "后一天 ►",
      showCalendar: "🗓️ 查看日历",
      hideCalendar: "🗓️ 隐藏日历",
      prevMonth: "‹ 上个月",
      nextMonth: "下个月 ›",
      tutor: "监护人:",
      present: "出勤",
      absent: "缺勤",
      noStudentsInClass: "该班级暂无登记的学生。",
      attendanceSummary: "考勤统计摘要",
      presentCountLabel: "人出勤",
      absentCountLabel: "人缺勤",
      montessoriTipTitle: "每日蒙台梭利育儿小贴士",
      montessoriTipText: '"任何不必要的协助都是对儿童发展的阻碍。" 在帮孩子扣扣子前，请给予他们 3 次自主尝试的机会。',
      teachingSection: "教学专区",
      studentsManagementTitle: "学生管理与档案",
      studentsManagementSubtitle: "查看儿童信息、发送日志评论并分配活动或材料。",
      searchStudentPlaceholder: "搜索学生或家长...",
      noStudentsFound: "未找到符合条件的学生。",
      tutorLabel: "家长:",
      genderLabel: "性别",
      girl: "👧 女孩",
      boy: "👦 男孩",
      ageLabel: "年龄",
      assignedClassroomLabel: "分配教室",
      unassignedClassroom: "未分配教室",
      sendNoteBtn: "💬 发送评论至日志",
      assignTaskBtn: "📋 分配活动或材料",
      planningHeader: "教学计划与日历",
      curriculumTitle: "课程计划 -",
      allClassrooms: "所有班级",
      curriculumSubtitle: "按日期安排主题与活动，自动同步至家长日历。",
      searchCurriculumPlaceholder: "在课程计划中搜索...",
      addCurriculumBtn: "+ 安排活动",
      noCurriculumEvents: "课程计划中暂无活动。点击 \"+ 安排活动\" 添加新活动。",
      deleteEventTitle: "从课程计划中删除",
      deleteBtn: "删除",
      reportsHeader: "家校沟通与消息",
      reportsTitle: "考勤报告与留言 -",
      reportsSubtitle: "查看家长发送的健康通知、请假或留言，并直接回复。",
      totalMessages: "条消息",
      filterByTutor: "👨‍👩‍👧‍👦 按学生家长筛选:",
      allTutors: "🌐 所有家长",
      noReportsForTutor: "所选家长暂无报告或留言。",
      pendingResponse: "等待教师回复",
      replyToTutor: "回复家长",
      modifyReply: "修改回复",
      noteModalTitle: "💬 发送评论至日志",
      targetStudentLabel: "接收学生:",
      writeNoteLabel: "填写您的教学观察或评语:",
      notePlaceholder: "例如：热衷于探索感官材料，积极参与日常活动...",
      sendToLogBtn: "发送至日志",
      cancelBtn: "取消",
      taskModalTitle: "📋 分配活动或材料",
      assignToLabel: "分配给:",
      taskTitleLabel: "材料或任务标题:",
      taskTitlePlaceholder: "例如：疯狂帽子节的可回收材料...",
      taskSubtitleLabel: "附加说明/备注:",
      taskSubtitlePlaceholder: "例如：截至10月31日星期二",
      taskIconLabel: "代表图标:",
      assignToCalendarBtn: "添加至日历",
      currModalTitle: "📅 安排课程活动",
      currTitleLabel: "活动或主题标题:",
      currTitlePlaceholder: "例如：造型表达与触觉工作坊...",
      currDateLabel: "日期:",
      currTimeLabel: "时间:",
      currTimePlaceholder: "例如：09:00 AM - 10:30 AM",
      currCategoryLabel: "领域/分类:",
      catWorkshops: "AMI早教（工作坊）",
      catSpecial: "游戏/园艺/特别活动",
      catMeetings: "家长会议/机构活动",
      catAcademic: "学术领域/表达",
      currDescLabel: "教学说明或观察:",
      currDescPlaceholder: "详细说明当天的教学目标或学生任务...",
      saveToCalendarBtn: "保存至日历",
      replyModalTitle: "💬 回复",
      tutorInquiryLabel: "家长咨询:",
      replyStatusLabel: "回复状态标签:",
      optAttended: "✓ 已处理/已获悉",
      optDose: "💊 药物已按时服用",
      optPermission: "⏰ 时间/请假已批准",
      optObs: "📝 已记录在案",
      replyMessageLabel: "给家长的回复或消息:",
      replyPlaceholder: "填写显示在家长面板上的回复...",
      sendReplyBtn: "发送回复",
      nav: {
        dashboard: "仪表盘",
        students: "学生列表",
        curriculum: "课程计划",
        evaluations: "教学评估",
        reports: "考勤报告"
      }
    }
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('montekids_language') || 'es';
  });

  useEffect(() => {
    localStorage.setItem('montekids_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (path, fallback = '') => {
    const keys = path.split('.');
    let current = translations[language];
    for (const key of keys) {
      if (!current || current[key] === undefined) {
        let fallbackVal = translations['es'];
        for (const fKey of keys) {
          if (!fallbackVal || fallbackVal[fKey] === undefined) return fallback;
          fallbackVal = fallbackVal[fKey];
        }
        return fallbackVal || fallback;
      }
      current = current[key];
    }
    return current || fallback;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'es',
      setLanguage: () => {},
      t: (path, fallback = '') => fallback
    };
  }
  return context;
}
